/*
 * a253316.c -- count 2n x 2n Takuzu grids (OEIS A253316).
 *
 * A Takuzu (Binairo) grid is a 2n x 2n 0/1 matrix in which
 *   (1) every row and every column contains n zeros and n ones,
 *   (2) no row or column contains three consecutive equal entries,
 *   (3) all rows are distinct and all columns are distinct.
 *
 * Known terms, n = 0..5:  1, 2, 72, 4140, 4111116, 48183195384.
 *
 * ALGORITHM
 * ---------
 * Split the grid at the "seam" between rows n and n+1.  For every ordered pair
 * (x, y) of distinct valid lines placed at rows n and n+1:
 *
 *  1. Enumerate every top half T (rows 1..n, ending in x) and every bottom half
 *     B (rows n+1..2n, starting with y) such that the half has distinct valid
 *     rows, no column of the half has three equal consecutive entries, no
 *     column gets three equal entries across the seam, T does not use row y
 *     and B does not use row x.
 *  2. Group halves by their per-column one-counts.  T and B fit together only
 *     if the counts add up to n in every column (a dense mixed-radix index of
 *     the count vector is used as the group key).
 *  3. Inside a group, count the pairs (T, B) that also satisfy
 *       - columns distinct: no column pair (j,k) equal in T *and* equal in B;
 *       - rows distinct:    no row of T (besides x) equal to a row of B.
 *     Every half is summarised by a bit mask of its equal column pairs and its
 *     list of rows ("features").  Two columns can only coincide if they agree
 *     in both seam rows x and y, so the pair masks are restricted to those
 *     pairs up front.  For one side of the group we build a bitset per feature
 *     over the halves that have it; the conflicts of a half on the other side
 *     are the OR of the bitsets of its features (NEON-vectorised), so a
 *     candidate pair costs roughly (6 features / 64) bit operations.
 *     Large groups instead use inclusion-exclusion over the set of shared
 *     rows, with histograms over the distinct pair masks, which is linear in
 *     the number of halves (see join_group_ie).  --join selects the method;
 *     the two were cross-checked on every n = 6 work unit.
 *
 * Seams are reduced by the symmetry group generated by complementing all
 * entries, mirroring left/right and mirroring top/bottom (order 8).  Each
 * canonical seam is an independent work unit; results are appended to a
 * checkpoint file as units complete, so a run can be stopped (Ctrl-C) and
 * resumed later by running the same command again.
 *
 * Supports 1 <= n <= 6 (n = 6, i.e. 12 x 12, is the first unknown term).
 */

#include <errno.h>
#include <inttypes.h>
#include <math.h>
#include <pthread.h>
#include <signal.h>
#include <stdarg.h>
#include <stdatomic.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/file.h>
#include <sys/time.h>
#include <time.h>
#include <unistd.h>
#if defined(__APPLE__)
#include <sys/sysctl.h>
#endif
#if defined(__ARM_NEON)
#include <arm_neon.h>
#endif

typedef unsigned __int128 u128;

#define MAXN      6
#define MAXC      (2 * MAXN)                /* max grid side                  */
#define MAXR      256                       /* max #valid lines (208, n = 6)  */
#define MAXPAIRS  (MAXC * (MAXC - 1) / 2)   /* column pairs (66, n = 6)       */
#define MAXFEAT   (MAXPAIRS + MAXR)
#define NO_GID    0xFFFFFFFFu
#define CHUNK     32768                     /* bitset-side tile (records)     */

static const char *KNOWN[] = { "1", "2", "72", "4140", "4111116", "48183195384" };
#define NKNOWN ((int)(sizeof KNOWN / sizeof KNOWN[0]))

/* ------------------------------------------------------------------------ */
/* utilities                                                                */
/* ------------------------------------------------------------------------ */

static double now_sec(void)
{
    struct timeval tv;
    gettimeofday(&tv, NULL);
    return tv.tv_sec + tv.tv_usec * 1e-6;
}

static void die(const char *fmt, ...)
{
    va_list ap;
    va_start(ap, fmt);
    fprintf(stderr, "error: ");
    vfprintf(stderr, fmt, ap);
    fprintf(stderr, "\n");
    va_end(ap);
    exit(1);
}

static void *xmalloc(size_t sz)
{
    void *p = malloc(sz ? sz : 1);
    if (!p) die("out of memory allocating %zu bytes", sz);
    return p;
}

static void *xrealloc(void *p, size_t sz)
{
    p = realloc(p, sz ? sz : 1);
    if (!p) die("out of memory reallocating %zu bytes", sz);
    return p;
}

static char *u128_str(u128 v, char *buf) /* buf >= 48 bytes */
{
    char tmp[48];
    int i = 0;
    if (v == 0) tmp[i++] = '0';
    while (v) { tmp[i++] = (char)('0' + (int)(v % 10)); v /= 10; }
    for (int j = 0; j < i; j++) buf[j] = tmp[i - 1 - j];
    buf[i] = 0;
    return buf;
}

static bool parse_u128(const char *s, u128 *out)
{
    u128 v = 0;
    if (!*s) return false;
    for (; *s; s++) {
        if (*s < '0' || *s > '9') return false;
        v = v * 10 + (u128)(*s - '0');
    }
    *out = v;
    return true;
}

static void fmt_dur(double s, char *buf, size_t sz)
{
    if (s < 0 || s != s || s > 1e9) { snprintf(buf, sz, "?"); return; }
    long t = (long)(s + 0.5);
    long d = t / 86400, h = (t / 3600) % 24, m = (t / 60) % 60, x = t % 60;
    if (d) snprintf(buf, sz, "%ldd%02ldh%02ldm", d, h, m);
    else if (h) snprintf(buf, sz, "%ldh%02ldm%02lds", h, m, x);
    else if (m) snprintf(buf, sz, "%ldm%02lds", m, x);
    else snprintf(buf, sz, "%lds", x);
}

static int ncpu(void)
{
    long c = sysconf(_SC_NPROCESSORS_ONLN);
    return c > 0 ? (int)c : 1;
}

static double physmem_gb(void)
{
#if defined(__APPLE__)
    uint64_t mem = 0;
    size_t len = sizeof mem;
    if (sysctlbyname("hw.memsize", &mem, &len, NULL, 0) == 0) return mem / 1073741824.0;
#elif defined(_SC_PHYS_PAGES)
    long pages = sysconf(_SC_PHYS_PAGES), psz = sysconf(_SC_PAGESIZE);
    if (pages > 0 && psz > 0) return (double)pages * psz / 1073741824.0;
#endif
    return 8.0;
}

/* ------------------------------------------------------------------------ */
/* problem tables                                                           */
/* ------------------------------------------------------------------------ */

static int n, N, nR, E;               /* half size, side, #lines, #col pairs */
static uint32_t lineBits[MAXR];       /* valid lines as bit masks            */
static uint32_t lineDense[MAXR];      /* contribution to dense count index   */
static u128 lineAgree[MAXR];          /* bit p: columns of pair p are equal  */
static int lineCompl[MAXR], lineRev[MAXR];
static uint32_t *adjStart;            /* CSR: (a,b) -> c, no column a=b=c    */
static uint8_t *adjList;
static int cntLo, cntHi, cntBase;     /* range of #ones in a half column     */
static uint32_t denseSize, denseSB;   /* base^N, sum_j base^j                */
static int gidShift;                  /* record = eq | rows<<E | gid<<shift  */
static uint64_t gidLimit;
static u128 eqMask;

static int valid_line(uint32_t x, int len, int ones)
{
    if (ones >= 0 && __builtin_popcount(x) != ones) return 0;
    for (int i = 0; i + 2 < len; i++) {
        uint32_t t = (x >> i) & 7;
        if (t == 0 || t == 7) return 0;
    }
    return 1;
}

static void init_tables(int half)
{
    n = half;
    N = 2 * n;
    uint32_t mask = (1u << N) - 1;
    static int idx[1 << MAXC];

    nR = 0;
    for (uint32_t x = 0; x <= mask; x++) {
        idx[x] = -1;
        if (valid_line(x, N, n)) { idx[x] = nR; lineBits[nR++] = x; }
    }
    if (nR > MAXR) die("too many lines");

    /* range of one-counts in an n-long piece of a column with no 000/111 */
    cntLo = n; cntHi = 0;
    for (uint32_t x = 0; x < (1u << n); x++)
        if (valid_line(x, n, -1)) {
            int c = __builtin_popcount(x);
            if (c < cntLo) cntLo = c;
            if (c > cntHi) cntHi = c;
        }
    cntBase = cntHi - cntLo + 1;
    denseSB = 0;
    uint64_t pw = 1;
    for (int j = 0; j < N; j++) { denseSB += (uint32_t)pw; pw *= (uint64_t)cntBase; }
    if (pw > (1u << 30)) die("dense index too large");
    denseSize = (uint32_t)pw;

    E = N * (N - 1) / 2;
    int pj[MAXPAIRS], pk[MAXPAIRS], p = 0;
    for (int j = 0; j < N; j++)
        for (int k = j + 1; k < N; k++) { pj[p] = j; pk[p] = k; p++; }

    for (int r = 0; r < nR; r++) {
        uint32_t x = lineBits[r];
        uint32_t d = 0, pwj = 1;
        for (int j = 0; j < N; j++) { d += ((x >> j) & 1) * pwj; pwj *= (uint32_t)cntBase; }
        lineDense[r] = d;
        u128 ag = 0;
        for (int q = 0; q < E; q++)
            if (((x >> pj[q]) & 1) == ((x >> pk[q]) & 1)) ag |= (u128)1 << q;
        lineAgree[r] = ag;
        lineCompl[r] = idx[~x & mask];
        uint32_t rv = 0;
        for (int j = 0; j < N; j++) if ((x >> j) & 1) rv |= 1u << (N - 1 - j);
        lineRev[r] = idx[rv];
    }

    /* ordered pair (a,b) -> rows c != a,b with no column a=b=c */
    size_t np = (size_t)nR * nR;
    adjStart = xmalloc((np + 1) * sizeof *adjStart);
    size_t tot = 0;
    for (int pass = 0; pass < 2; pass++) {
        tot = 0;
        for (int a = 0; a < nR; a++)
            for (int b = 0; b < nR; b++) {
                if (pass == 0) adjStart[(size_t)a * nR + b] = (uint32_t)tot;
                uint32_t same = ~(lineBits[a] ^ lineBits[b]) & mask;
                for (int c = 0; c < nR; c++) {
                    if (c == a || c == b) continue;
                    if (same & ~(lineBits[b] ^ lineBits[c]) & mask) continue;
                    if (pass == 1) adjList[tot] = (uint8_t)c;
                    tot++;
                }
            }
        if (pass == 0) { adjStart[np] = (uint32_t)tot; adjList = xmalloc(tot + 1); }
    }

    gidShift = E + 8 * (n - 1);
    gidLimit = (128 - gidShift >= 32) ? 0xFFFFFFFEull : ((1ull << (128 - gidShift)) - 1);
    eqMask = (((u128)1) << E) - 1;
}

/* ------------------------------------------------------------------------ */
/* work units: canonical seams under the order-8 symmetry group             */
/* ------------------------------------------------------------------------ */

typedef struct {
    int x, y, weight;
    double estT, estB, cost;
} Unit;

static Unit *units;
static int nUnits;

/* halfCnt[a*nR+b]: #n-row half sequences whose rows next to the seam are
 * (a = second, b = seam row); only local distinctness, so an upper bound */
static double *halfCnt;

static void compute_half_counts(void)
{
    size_t np = (size_t)nR * nR;
    halfCnt = xmalloc(np * sizeof *halfCnt);
    double *nx = xmalloc(np * sizeof *nx);
    if (n == 1) {
        for (size_t i = 0; i < np; i++) halfCnt[i] = 1;   /* unused */
        free(nx);
        return;
    }
    for (int a = 0; a < nR; a++)
        for (int b = 0; b < nR; b++) halfCnt[(size_t)a * nR + b] = (a != b);
    /* f_{L+1}(b,c) = sum_a f_L(a,b); here (a,b) = (older, newer) */
    for (int L = 3; L <= n; L++) {
        memset(nx, 0, np * sizeof *nx);
        for (int a = 0; a < nR; a++)
            for (int b = 0; b < nR; b++) {
                double v = halfCnt[(size_t)a * nR + b];
                if (v == 0) continue;
                size_t p = (size_t)a * nR + b;
                for (uint32_t i = adjStart[p]; i < adjStart[p + 1]; i++)
                    nx[(size_t)b * nR + adjList[i]] += v;
            }
        double *t = halfCnt; halfCnt = nx; nx = t;
    }
    free(nx);
    /* halfCnt[(newest-1)*nR + newest]; by reversal symmetry the number of
     * sequences starting (s, a) equals the number ending (a, s). */
}

static double est_half(int s, uint32_t D)
{
    if (n == 1) return 1;
    uint32_t mask = (1u << N) - 1;
    double t = 0;
    for (int a = 0; a < nR; a++) {
        if (a == s) continue;
        if (~(lineBits[a] ^ lineBits[s]) & D & mask) continue;
        t += halfCnt[(size_t)a * nR + s];
    }
    return t;
}

static int cmp_unit_cost_desc(const void *pa, const void *pb)
{
    const Unit *a = pa, *b = pb;
    if (a->cost > b->cost) return -1;
    if (a->cost < b->cost) return 1;
    if (a->x != b->x) return a->x - b->x;
    return a->y - b->y;
}

static void build_units(bool useSym)
{
    uint32_t mask = (1u << N) - 1;
    units = xmalloc((size_t)nR * nR * sizeof *units);
    nUnits = 0;
    long wsum = 0;
    for (int x = 0; x < nR; x++)
        for (int y = 0; y < nR; y++) {
            if (x == y) continue;
            int w = 1;
            if (useSym) {
                int gx[4] = { x, lineCompl[x], lineRev[x], lineRev[lineCompl[x]] };
                int gy[4] = { y, lineCompl[y], lineRev[y], lineRev[lineCompl[y]] };
                long keys[8], self = (long)x * nR + y;
                int m = 0;
                bool canon = true;
                for (int g = 0; g < 4; g++) {
                    keys[m++] = (long)gx[g] * nR + gy[g];
                    keys[m++] = (long)gy[g] * nR + gx[g];
                }
                for (int i = 0; i < 8; i++) if (keys[i] < self) canon = false;
                if (!canon) continue;
                w = 0;
                for (int i = 0; i < 8; i++) {
                    bool dup = false;
                    for (int j = 0; j < i; j++) if (keys[j] == keys[i]) dup = true;
                    if (!dup) w++;
                }
            }
            Unit *u = &units[nUnits++];
            u->x = x; u->y = y; u->weight = w;
            uint32_t D = ~(lineBits[x] ^ lineBits[y]) & mask;
            u->estT = est_half(x, D);
            u->estB = est_half(y, D);
            /* time model from benchmarks: join ~ estT*estB, enumeration+sort ~ estT+estB */
            u->cost = u->estT * u->estB + 5e6 * (u->estT + u->estB);
            wsum += w;
        }
    if (wsum != (long)nR * (nR - 1)) die("internal: orbit weights sum to %ld", wsum);
}

/* ------------------------------------------------------------------------ */
/* per-thread worker state                                                  */
/* ------------------------------------------------------------------------ */

typedef struct {
    /* halves of the current pass */
    u128 *T, *B;
    size_t Tn, Tcap, Bn, Bcap;
    /* groups */
    uint32_t *gidOf;            /* dense count index -> gid (NO_GID)       */
    uint32_t *gidIdx;           /* gid -> dense index                       */
    uint32_t *cntT, *cntB;
    size_t *startT, *startB, *nextPos;
    size_t gcap;
    uint32_t ng;
    /* bitset join scratch */
    uint64_t *bits;
    size_t bitsCap;
    int16_t featSlot[MAXFEAT];
    int usedFeat[MAXFEAT];
    /* inclusion-exclusion join scratch */
    u128 *mmKey;                /* mask -> id hash map (stamped entries)     */
    uint32_t *mmVal, *mmStamp, mmCur;
    size_t mmCap;
    uint32_t *idT, *idB, *ident;/* mask id per record, identity index list  */
    u128 *maskT, *maskB;        /* distinct masks of each side              */
    size_t idCap;
    uint8_t *dj;                /* dj[a*dB+b]: masks a, b disjoint          */
    size_t djCap;
    uint32_t dT, dB;
    uint32_t *hx, *hy, *touchX, *touchY;  /* histograms, kept zero         */
    uint32_t *lst[2][MAXN];     /* per-depth partition lists                */
    size_t lstCap;
    uint32_t ieCnt[MAXN][2][MAXR], ieOff[MAXN][2][MAXR];
    uint8_t ieTouch[MAXN][MAXR];
    uint64_t ieGroups, bsGroups;
    /* DFS state */
    int h[MAXN];
    uint8_t used[MAXR];
    uint8_t lvl1[MAXR];
    int nlvl1;
    int side, K, pass;
    bool overflow;
    /* statistics */
    u128 pairMass;              /* candidate pairs (count vectors match)    */
    uint64_t nHalfT, nHalfB, nGroups;
    double tEnum, tSort, tJoin;
    /* progress, read by the monitor thread */
    _Atomic int curUnit;        /* index into units[], -1 when idle         */
    _Atomic uint64_t progPpm;   /* completed fraction of the unit, x1e6     */
    int id;
} Worker;

static void worker_init(Worker *w, int id)
{
    memset(w, 0, sizeof *w);
    w->id = id;
    w->gidOf = xmalloc((size_t)denseSize * sizeof *w->gidOf);
    for (uint32_t i = 0; i < denseSize; i++) w->gidOf[i] = NO_GID;
    w->gcap = 1024;
    w->gidIdx = xmalloc(w->gcap * sizeof *w->gidIdx);
    w->cntT = xmalloc(w->gcap * sizeof *w->cntT);
    w->cntB = xmalloc(w->gcap * sizeof *w->cntB);
    w->startT = xmalloc((w->gcap + 1) * sizeof *w->startT);
    w->startB = xmalloc((w->gcap + 1) * sizeof *w->startB);
    w->nextPos = xmalloc((w->gcap + 1) * sizeof *w->nextPos);
    for (int f = 0; f < MAXFEAT; f++) w->featSlot[f] = -1;
    atomic_store(&w->curUnit, -1);
}

static void worker_free(Worker *w)
{
    free(w->T); free(w->B); free(w->gidOf); free(w->gidIdx); free(w->cntT); free(w->cntB);
    free(w->startT); free(w->startB); free(w->nextPos); free(w->bits);
    free(w->mmKey); free(w->mmVal); free(w->mmStamp); free(w->idT); free(w->idB); free(w->ident);
    free(w->maskT); free(w->maskB); free(w->dj); free(w->hx); free(w->hy); free(w->touchX); free(w->touchY);
    for (int d = 0; d < MAXN; d++) { free(w->lst[0][d]); free(w->lst[1][d]); }
}

static void grow_groups(Worker *w)
{
    size_t nc = w->gcap * 2;
    w->gidIdx = xrealloc(w->gidIdx, nc * sizeof *w->gidIdx);
    w->cntT = xrealloc(w->cntT, nc * sizeof *w->cntT);
    w->cntB = xrealloc(w->cntB, nc * sizeof *w->cntB);
    w->startT = xrealloc(w->startT, (nc + 1) * sizeof *w->startT);
    w->startB = xrealloc(w->startB, (nc + 1) * sizeof *w->startB);
    w->nextPos = xrealloc(w->nextPos, (nc + 1) * sizeof *w->nextPos);
    w->gcap = nc;
}

static inline uint32_t pass_of(uint32_t idx, int K)
{
    return (uint32_t)((((uint64_t)idx * 0x9E3779B97F4A7C15ull) >> 32) % (uint64_t)K);
}

/* ------------------------------------------------------------------------ */
/* half enumeration                                                         */
/* ------------------------------------------------------------------------ */

static inline void emit_half(Worker *w, uint32_t dsum, u128 agree)
{
    uint32_t idx;
    if (w->side == 0) idx = dsum - (uint32_t)cntLo * denseSB;
    else              idx = (uint32_t)(n - cntLo) * denseSB - dsum;   /* complementary key */
    if (w->K > 1 && pass_of(idx, w->K) != (uint32_t)w->pass) return;
    uint32_t g = w->gidOf[idx];
    if (w->side == 0) {
        if (g == NO_GID) {
            if (w->ng >= gidLimit) { w->overflow = true; return; }
            if (w->ng >= w->gcap) grow_groups(w);
            g = w->ng++;
            w->gidOf[idx] = g;
            w->gidIdx[g] = idx;
            w->cntT[g] = 0;
            w->cntB[g] = 0;
        }
        w->cntT[g]++;
    } else {
        if (g == NO_GID) return;
        w->cntB[g]++;
    }
    uint64_t rows = 0;
    for (int i = 1; i < n; i++) rows |= (uint64_t)w->h[i] << (8 * (i - 1));
    u128 rec = agree | ((u128)rows << E) | ((u128)g << gidShift);
    if (w->side == 0) {
        if (w->Tn == w->Tcap) { w->Tcap = w->Tcap * 3 / 2 + 1024; w->T = xrealloc(w->T, w->Tcap * sizeof(u128)); }
        w->T[w->Tn++] = rec;
    } else {
        if (w->Bn == w->Bcap) { w->Bcap = w->Bcap * 3 / 2 + 1024; w->B = xrealloc(w->B, w->Bcap * sizeof(u128)); }
        w->B[w->Bn++] = rec;
    }
}

static void dfs_half(Worker *w, int k, uint32_t dsum, u128 agree)
{
    if (k == n) { emit_half(w, dsum, agree); return; }
    const uint8_t *lst;
    uint32_t cnt;
    if (k == 1) { lst = w->lvl1; cnt = (uint32_t)w->nlvl1; }
    else {
        size_t p = (size_t)w->h[k - 2] * nR + w->h[k - 1];
        lst = adjList + adjStart[p];
        cnt = adjStart[p + 1] - adjStart[p];
    }
    for (uint32_t i = 0; i < cnt; i++) {
        int r = lst[i];
        if (w->used[r]) continue;
        w->used[r] = 1;
        w->h[k] = r;
        dfs_half(w, k + 1, dsum + lineDense[r], agree & lineAgree[r]);
        w->used[r] = 0;
    }
}

/* enumerate halves whose seam row is s, avoiding row 'forbid' */
static void enum_side(Worker *w, int side, int s, int forbid, uint32_t D)
{
    uint32_t mask = (1u << N) - 1;
    w->side = side;
    w->nlvl1 = 0;
    for (int a = 0; a < nR; a++) {
        if (a == s || a == forbid) continue;
        if (~(lineBits[a] ^ lineBits[s]) & D & mask) continue;   /* seam triple */
        w->lvl1[w->nlvl1++] = (uint8_t)a;
    }
    memset(w->used, 0, sizeof w->used);
    w->used[s] = 1;
    w->used[forbid] = 1;
    w->h[0] = s;
    /* a column pair can only clash if it is equal in both halves, hence equal
     * in both seam rows: keep only pairs on which the other seam row agrees */
    dfs_half(w, 1, lineDense[s], lineAgree[s] & lineAgree[forbid]);
}

/* ------------------------------------------------------------------------ */
/* grouping (in-place counting sort by gid)                                 */
/* ------------------------------------------------------------------------ */

#define REC_GID(r) ((uint32_t)((r) >> gidShift))

static void sort_by_gid(u128 *a, uint32_t ng, const uint32_t *cnt, size_t *start, size_t *next)
{
    start[0] = 0;
    for (uint32_t g = 0; g < ng; g++) start[g + 1] = start[g] + cnt[g];
    for (uint32_t g = 0; g < ng; g++) next[g] = start[g];
    for (uint32_t g = 0; g < ng; g++) {
        while (next[g] < start[g + 1]) {
            u128 v = a[next[g]];
            uint32_t gv = REC_GID(v);
            while (gv != g) {
                u128 t = a[next[gv]];
                a[next[gv]++] = v;
                v = t;
                gv = REC_GID(v);
            }
            a[next[g]++] = v;
        }
    }
}

/* ------------------------------------------------------------------------ */
/* counting compatible pairs inside a group                                 */
/* ------------------------------------------------------------------------ */

static inline int rec_features(u128 r, int *feat)
{
    int k = 0;
    u128 eq = r & eqMask;
    uint64_t e0 = (uint64_t)eq, e1 = (uint64_t)(eq >> 64);
    while (e0) { feat[k++] = __builtin_ctzll(e0); e0 &= e0 - 1; }
    while (e1) { feat[k++] = 64 + __builtin_ctzll(e1); e1 &= e1 - 1; }
    uint64_t rows = (uint64_t)(r >> E);
    for (int i = 1; i < n; i++) { feat[k++] = E + (int)(rows & 0xFF); rows >>= 8; }
    return k;
}

/* number of bits set in (ptr[0] | ... | ptr[m-1]) over W words */
static inline uint64_t or_popcount(const uint64_t *const *ptr, int m, size_t W)
{
    uint64_t total = 0;
    size_t wd = 0;
#if defined(__ARM_NEON)
    if (W >= 4) {
        uint16x8_t c0 = vdupq_n_u16(0), c1 = vdupq_n_u16(0);
        for (; wd + 4 <= W; wd += 4) {          /* W <= CHUNK/64: no u16 overflow */
            uint64x2_t v0 = vld1q_u64(ptr[0] + wd), v1 = vld1q_u64(ptr[0] + wd + 2);
            for (int q = 1; q < m; q++) {
                v0 = vorrq_u64(v0, vld1q_u64(ptr[q] + wd));
                v1 = vorrq_u64(v1, vld1q_u64(ptr[q] + wd + 2));
            }
            c0 = vpadalq_u8(c0, vcntq_u8(vreinterpretq_u8_u64(v0)));
            c1 = vpadalq_u8(c1, vcntq_u8(vreinterpretq_u8_u64(v1)));
        }
        total = vaddlvq_u16(c0) + vaddlvq_u16(c1);
    }
#endif
    for (; wd < W; wd++) {
        uint64_t v = ptr[0][wd];
        for (int q = 1; q < m; q++) v |= ptr[q][wd];
        total += (uint64_t)__builtin_popcountll(v);
    }
    return total;
}

/* S: records turned into per-feature bitsets (s <= CHUNK); L: probed records */
static uint64_t join_chunk(Worker *w, const u128 *S, size_t s, const u128 *L, size_t l)
{
    size_t W = (s + 63) >> 6;
    int nslots = 0;
    int feat[MAXPAIRS + MAXN];

    if (w->bitsCap < (size_t)MAXFEAT * W) {
        w->bitsCap = (size_t)MAXFEAT * W;
        free(w->bits);
        w->bits = xmalloc(w->bitsCap * sizeof(uint64_t));
    }
    uint64_t *bits = w->bits;

    for (size_t i = 0; i < s; i++) {
        int k = rec_features(S[i], feat);
        uint64_t bit = 1ull << (i & 63);
        size_t wd = i >> 6;
        for (int q = 0; q < k; q++) {
            int f = feat[q];
            int slot = w->featSlot[f];
            if (slot < 0) {
                slot = nslots++;
                w->featSlot[f] = (int16_t)slot;
                w->usedFeat[slot] = f;
                memset(bits + (size_t)slot * W, 0, W * sizeof(uint64_t));
            }
            bits[(size_t)slot * W + wd] |= bit;
        }
    }

    uint64_t total = 0;
    const uint64_t *ptr[MAXPAIRS + MAXN];
    for (size_t j = 0; j < l; j++) {
        int k = rec_features(L[j], feat), m = 0;
        for (int q = 0; q < k; q++) {
            int slot = w->featSlot[feat[q]];
            if (slot >= 0) ptr[m++] = bits + (size_t)slot * W;
        }
        if (m == 0) { total += s; continue; }
        uint64_t conf;
        if (W == 1) {
            uint64_t v = 0;
            for (int q = 0; q < m; q++) v |= ptr[q][0];
            conf = (uint64_t)__builtin_popcountll(v);
        } else conf = or_popcount(ptr, m, W);
        total += s - conf;
    }

    for (int q = 0; q < nslots; q++) w->featSlot[w->usedFeat[q]] = -1;
    return total;
}

/* reference implementation (--join brute): test every pair directly */
enum { JOIN_AUTO, JOIN_BITSET, JOIN_IE, JOIN_BRUTE };
static int joinMode = JOIN_AUTO;
static double ieMin = 6400;           /* auto: inclusion-exclusion if A*B > ieMin*(A+B) */

static uint64_t join_group_brute(const u128 *T, size_t A, const u128 *B, size_t Bn)
{
    uint64_t total = 0;
    for (size_t i = 0; i < A; i++) {
        uint64_t rs[MAXR / 64] = { 0 };
        uint64_t rows = (uint64_t)(T[i] >> E);
        for (int k = 1; k < n; k++) { int v = (int)(rows & 0xFF); rows >>= 8; rs[v >> 6] |= 1ull << (v & 63); }
        u128 eqT = T[i] & eqMask;
        for (size_t j = 0; j < Bn; j++) {
            if (eqT & B[j] & eqMask) continue;                 /* two equal columns */
            uint64_t rb = (uint64_t)(B[j] >> E);
            bool clash = false;
            for (int k = 1; k < n; k++) {
                int v = (int)(rb & 0xFF);
                rb >>= 8;
                if (rs[v >> 6] >> (v & 63) & 1) clash = true;    /* repeated row */
            }
            if (!clash) total++;
        }
    }
    return total;
}


/* ------------------------------------------------------------------------ */
/* counting compatible pairs, method 2: inclusion-exclusion over shared rows */
/* ------------------------------------------------------------------------ */
/*
 * clean(T,B) = sum over sets R of row values of (-1)^|R| * E(T_R, B_R), where
 * T_R are the halves containing every row of R and E(X,Y) is the number of
 * pairs of X x Y whose equal-column-pair masks are disjoint.  E comes from
 * histograms over the distinct masks of each side and a table of which
 * distinct masks are disjoint.  R is generated in increasing order:
 *     f(X, Y, m) = E(X, Y) - sum_{v > m} f(X_v, Y_v, v),   clean = f(T, B, -1).
 * The cost is linear in the number of halves (times the <= 2^(n-1) subsets
 * of rows they share) instead of proportional to the number of pairs.
 */

#define IE_DIRECT 48                  /* |X|*|Y| at or below: direct pairs    */
#define DJ_MAX    (1u << 24)          /* largest distinct-mask table          */

static inline uint64_t mask_hash(u128 m)
{
    uint64_t h = (uint64_t)m * 0x9E3779B97F4A7C15ull ^ (uint64_t)(m >> 64) * 0xC2B2AE3D27D4EB4Full;
    return h ^ (h >> 31);
}

/* ids[i] = index of the distinct mask of R[i]; returns #distinct masks */
static uint32_t assign_ids(Worker *w, const u128 *R, size_t cnt, uint32_t *ids, u128 *masks)
{
    size_t cap = 64;
    while (cap < 2 * cnt) cap <<= 1;
    if (cap > w->mmCap) {
        free(w->mmKey); free(w->mmVal); free(w->mmStamp);
        w->mmKey = xmalloc(cap * sizeof(u128));
        w->mmVal = xmalloc(cap * sizeof(uint32_t));
        w->mmStamp = calloc(cap, sizeof(uint32_t));
        if (!w->mmStamp) die("out of memory");
        w->mmCap = cap;
        w->mmCur = 0;
    }
    if (++w->mmCur == 0) { memset(w->mmStamp, 0, w->mmCap * sizeof(uint32_t)); w->mmCur = 1; }
    uint32_t cur = w->mmCur, d = 0;
    size_t hm = cap - 1;
    for (size_t i = 0; i < cnt; i++) {
        u128 m = R[i] & eqMask;
        size_t h = mask_hash(m) & hm;
        for (;;) {
            if (w->mmStamp[h] != cur) {
                w->mmStamp[h] = cur;
                w->mmKey[h] = m;
                w->mmVal[h] = d;
                masks[d] = m;
                ids[i] = d++;
                break;
            }
            if (w->mmKey[h] == m) { ids[i] = w->mmVal[h]; break; }
            h = (h + 1) & hm;
        }
    }
    return d;
}

/* pairs of X x Y with disjoint masks (E above) */
static uint64_t ie_eq_clean(Worker *w, const uint32_t *X, size_t nx, const uint32_t *Y, size_t ny)
{
    const uint32_t *idT = w->idT, *idB = w->idB;
    const uint8_t *dj = w->dj;
    uint32_t dB = w->dB, *hx = w->hx, *hy = w->hy;
    size_t tx = 0, ty = 0;
    for (size_t i = 0; i < nx; i++) { uint32_t a = idT[X[i]]; if (hx[a]++ == 0) w->touchX[tx++] = a; }
    for (size_t j = 0; j < ny; j++) { uint32_t b = idB[Y[j]]; if (hy[b]++ == 0) w->touchY[ty++] = b; }
    uint64_t sum = 0;
    for (size_t i = 0; i < tx; i++) {
        uint32_t a = w->touchX[i];
        const uint8_t *row = dj + (size_t)a * dB;
        uint64_t sb = 0;
        for (size_t j = 0; j < ty; j++) { uint32_t b = w->touchY[j]; sb += row[b] ? hy[b] : 0; }
        sum += (uint64_t)hx[a] * sb;
    }
    for (size_t i = 0; i < tx; i++) hx[w->touchX[i]] = 0;
    for (size_t j = 0; j < ty; j++) hy[w->touchY[j]] = 0;
    return sum;
}

/* pairs with disjoint masks and no common row greater than minRow */
static int64_t ie_direct(Worker *w, const u128 *T, const u128 *B, const uint32_t *X, size_t nx,
                         const uint32_t *Y, size_t ny, int minRow)
{
    int64_t cnt = 0;
    for (size_t i = 0; i < nx; i++) {
        uint64_t rs[MAXR / 64] = { 0 };
        uint64_t rows = (uint64_t)(T[X[i]] >> E);
        for (int k = 1; k < n; k++) {
            int v = (int)(rows & 0xFF);
            rows >>= 8;
            if (v > minRow) rs[v >> 6] |= 1ull << (v & 63);
        }
        const uint8_t *row = w->dj + (size_t)w->idT[X[i]] * w->dB;
        for (size_t j = 0; j < ny; j++) {
            if (!row[w->idB[Y[j]]]) continue;
            uint64_t rb = (uint64_t)(B[Y[j]] >> E);
            bool clash = false;
            for (int k = 1; k < n; k++) {
                int v = (int)(rb & 0xFF);
                rb >>= 8;
                if (rs[v >> 6] >> (v & 63) & 1) clash = true;
            }
            cnt += !clash;
        }
    }
    return cnt;
}

static int64_t ie_rec(Worker *w, const u128 *T, const u128 *B, const uint32_t *X, size_t nx,
                      const uint32_t *Y, size_t ny, int minRow, int depth)
{
    if (nx * ny <= IE_DIRECT) return ie_direct(w, T, B, X, nx, Y, ny, minRow);
    int64_t res = (int64_t)ie_eq_clean(w, X, nx, Y, ny);
    if (depth >= n - 1) return res;                 /* every row already shared */
    uint32_t *cx = w->ieCnt[depth][0], *cy = w->ieCnt[depth][1];
    uint32_t *ox = w->ieOff[depth][0], *oy = w->ieOff[depth][1];
    uint8_t *tv = w->ieTouch[depth];
    int ntv = 0;
    for (size_t i = 0; i < nx; i++) {
        uint64_t rows = (uint64_t)(T[X[i]] >> E);
        for (int k = 1; k < n; k++) {
            int v = (int)(rows & 0xFF);
            rows >>= 8;
            if (v > minRow && cx[v]++ == 0 && cy[v] == 0) tv[ntv++] = (uint8_t)v;
        }
    }
    for (size_t j = 0; j < ny; j++) {
        uint64_t rows = (uint64_t)(B[Y[j]] >> E);
        for (int k = 1; k < n; k++) {
            int v = (int)(rows & 0xFF);
            rows >>= 8;
            if (v > minRow && cy[v]++ == 0 && cx[v] == 0) tv[ntv++] = (uint8_t)v;
        }
    }
    uint32_t px = 0, py = 0;
    for (int t = 0; t < ntv; t++) {
        int v = tv[t];
        if (cx[v] && cy[v]) { ox[v] = px; px += cx[v]; oy[v] = py; py += cy[v]; }
    }
    if (px) {
        uint32_t *lx = w->lst[0][depth], *ly = w->lst[1][depth];
        for (size_t i = 0; i < nx; i++) {
            uint64_t rows = (uint64_t)(T[X[i]] >> E);
            for (int k = 1; k < n; k++) {
                int v = (int)(rows & 0xFF);
                rows >>= 8;
                if (v > minRow && cy[v]) lx[ox[v]++] = X[i];
            }
        }
        for (size_t j = 0; j < ny; j++) {
            uint64_t rows = (uint64_t)(B[Y[j]] >> E);
            for (int k = 1; k < n; k++) {
                int v = (int)(rows & 0xFF);
                rows >>= 8;
                if (v > minRow && cx[v]) ly[oy[v]++] = Y[j];
            }
        }
        for (int t = 0; t < ntv; t++) {
            int v = tv[t];
            if (cx[v] && cy[v]) {
                uint32_t sx = ox[v] - cx[v], sy = oy[v] - cy[v];
                res -= ie_rec(w, T, B, lx + sx, cx[v], ly + sy, cy[v], v, depth + 1);
            }
        }
    }
    for (int t = 0; t < ntv; t++) { cx[tv[t]] = 0; cy[tv[t]] = 0; }
    return res;
}

/* returns false if the distinct-mask table would be too large */
static bool join_group_ie(Worker *w, const u128 *T, size_t A, const u128 *B, size_t Bn, uint64_t *out)
{
    size_t need = A > Bn ? A : Bn;
    if (w->idCap < need) {
        free(w->idT); free(w->idB); free(w->ident); free(w->maskT); free(w->maskB);
        free(w->hx); free(w->hy); free(w->touchX); free(w->touchY);
        w->idCap = need + need / 2;
        w->idT = xmalloc(w->idCap * sizeof(uint32_t));
        w->idB = xmalloc(w->idCap * sizeof(uint32_t));
        w->ident = xmalloc(w->idCap * sizeof(uint32_t));
        for (size_t i = 0; i < w->idCap; i++) w->ident[i] = (uint32_t)i;
        w->maskT = xmalloc(w->idCap * sizeof(u128));
        w->maskB = xmalloc(w->idCap * sizeof(u128));
        w->hx = calloc(w->idCap, sizeof(uint32_t));
        w->hy = calloc(w->idCap, sizeof(uint32_t));
        w->touchX = xmalloc(w->idCap * sizeof(uint32_t));
        w->touchY = xmalloc(w->idCap * sizeof(uint32_t));
        if (!w->hx || !w->hy) die("out of memory");
    }
    w->dT = assign_ids(w, T, A, w->idT, w->maskT);
    w->dB = assign_ids(w, B, Bn, w->idB, w->maskB);
    size_t djn = (size_t)w->dT * w->dB;
    if (djn > DJ_MAX) return false;
    if (w->djCap < djn) { free(w->dj); w->djCap = djn + djn / 2; w->dj = xmalloc(w->djCap); }
    for (uint32_t a = 0; a < w->dT; a++) {
        u128 ma = w->maskT[a];
        uint8_t *row = w->dj + (size_t)a * w->dB;
        for (uint32_t b = 0; b < w->dB; b++) row[b] = (ma & w->maskB[b]) == 0;
    }
    size_t lneed = (size_t)(n - 1) * need;
    if (w->lstCap < lneed) {
        w->lstCap = lneed + lneed / 2;
        for (int d = 0; d < MAXN; d++) {
            free(w->lst[0][d]); free(w->lst[1][d]);
            w->lst[0][d] = xmalloc(w->lstCap * sizeof(uint32_t));
            w->lst[1][d] = xmalloc(w->lstCap * sizeof(uint32_t));
        }
    }
    int64_t r = ie_rec(w, T, B, w->ident, A, w->ident, Bn, -1, 0);
    if (r < 0) die("internal: negative inclusion-exclusion count");
    *out = (uint64_t)r;
    return true;
}

static uint64_t join_group(Worker *w, const u128 *T, size_t A, const u128 *B, size_t Bn)
{
    if (joinMode == JOIN_BRUTE) return join_group_brute(T, A, B, Bn);
    /* inclusion-exclusion is linear in A+B, bitsets cost ~ 6*A*B/64 */
    if (joinMode == JOIN_IE || (joinMode == JOIN_AUTO && (double)A * Bn > ieMin * (double)(A + Bn))) {
        uint64_t r;
        if (join_group_ie(w, T, A, B, Bn, &r)) { w->ieGroups++; return r; }
    }
    w->bsGroups++;
    const u128 *S, *L;
    size_t s, l;
    /* bitsets over the side that minimises (#probes) * (#bitset words) */
    if ((uint64_t)A * ((Bn + 63) / 64) <= (uint64_t)Bn * ((A + 63) / 64)) { S = B; s = Bn; L = T; l = A; }
    else { S = T; s = A; L = B; l = Bn; }
    uint64_t total = 0;
    for (size_t c0 = 0; c0 < s; c0 += CHUNK) {
        size_t cs = s - c0 < CHUNK ? s - c0 : CHUNK;
        total += join_chunk(w, S + c0, cs, L, l);
    }
    return total;
}

/* ------------------------------------------------------------------------ */
/* one work unit                                                            */
/* ------------------------------------------------------------------------ */

static volatile sig_atomic_t stopRequested = 0;
static size_t memBudgetPerThread;     /* bytes for half records per thread  */

static void reset_groups(Worker *w)
{
    for (uint32_t g = 0; g < w->ng; g++) w->gidOf[w->gidIdx[g]] = NO_GID;
    w->ng = 0;
    w->Tn = w->Bn = 0;
}

/* returns false if interrupted (result invalid) */
static bool run_unit(Worker *w, const Unit *u, uint64_t *result)
{
    uint32_t mask = (1u << N) - 1;
    uint32_t D = ~(lineBits[u->x] ^ lineBits[u->y]) & mask;
    double need = (u->estT + u->estB) * sizeof(u128) * 1.15;
    int K = (int)(need / (double)memBudgetPerThread) + 1;
    uint64_t total = 0;

    for (int attempt = 0;; attempt++) {
        bool redo = false;
        total = 0;
        for (int pass = 0; pass < K; pass++) {
            w->K = K;
            w->pass = pass;
            w->overflow = false;
            reset_groups(w);
            size_t wantT = (size_t)(u->estT / K * 1.05) + 1024;
            size_t wantB = (size_t)(u->estB / K * 1.05) + 1024;
            if (w->Tcap < wantT) { free(w->T); w->Tcap = wantT; w->T = xmalloc(wantT * sizeof(u128)); }
            if (w->Bcap < wantB) { free(w->B); w->Bcap = wantB; w->B = xmalloc(wantB * sizeof(u128)); }
            double ta = now_sec();
            enum_side(w, 0, u->x, u->y, D);
            if (w->overflow) { redo = true; break; }
            enum_side(w, 1, u->y, u->x, D);
            double tb = now_sec();
            w->tEnum += tb - ta;
            w->nHalfT += w->Tn;
            w->nHalfB += w->Bn;
            w->nGroups += w->ng;

            /* drop tops whose group has no bottom */
            size_t o = 0;
            for (size_t i = 0; i < w->Tn; i++) {
                u128 r = w->T[i];
                if (w->cntB[REC_GID(r)]) w->T[o++] = r;
            }
            w->Tn = o;
            for (uint32_t g = 0; g < w->ng; g++) if (!w->cntB[g]) w->cntT[g] = 0;
            sort_by_gid(w->T, w->ng, w->cntT, w->startT, w->nextPos);
            sort_by_gid(w->B, w->ng, w->cntB, w->startB, w->nextPos);
            double tc = now_sec();
            w->tSort += tc - tb;

            u128 mass = 0, done = 0;
            for (uint32_t g = 0; g < w->ng; g++) mass += (u128)w->cntT[g] * w->cntB[g];
            w->pairMass += mass;
            u128 lastReport = 0;
            for (uint32_t g = 0; g < w->ng; g++) {
                if (!w->cntT[g] || !w->cntB[g]) continue;
                total += join_group(w, w->T + w->startT[g], w->cntT[g], w->B + w->startB[g], w->cntB[g]);
                done += (u128)w->cntT[g] * w->cntB[g];
                if (done - lastReport > (u128)200000000u) {
                    lastReport = done;
                    double f = ((double)pass + (double)done / (double)mass) / K;
                    atomic_store(&w->progPpm, (uint64_t)(f * 1e6));
                    if (stopRequested) return false;
                }
            }
            w->tJoin += now_sec() - tc;
            atomic_store(&w->progPpm, (uint64_t)((pass + 1) * 1e6 / K));
            if (stopRequested) return false;
        }
        if (!redo) break;
        K *= 2;                               /* too many groups in one pass */
        if (attempt > 20) die("cannot fit unit into group-id space");
    }
    reset_groups(w);
    *result = total;
    return true;
}

/* ------------------------------------------------------------------------ */
/* checkpointing                                                            */
/* ------------------------------------------------------------------------ */

typedef struct {
    bool done;
    uint64_t count;
    double secs;
} UnitResult;

static UnitResult *results;           /* indexed by x*nR + y                 */
static FILE *ckptFile;
static char ckptPath[4096];
static pthread_mutex_t lock = PTHREAD_MUTEX_INITIALIZER;

static void ckpt_header(char *buf, size_t sz, bool useSym)
{
    snprintf(buf, sz, "A253316-checkpoint v1 n=%d lines=%d units=%d sym=%d", n, nR, nUnits, useSym ? 1 : 0);
}

/* open (creating if needed) and lock the checkpoint, then load finished units */
static int ckpt_init(bool useSym)
{
    char want[256];
    ckpt_header(want, sizeof want, useSym);
    ckptFile = fopen(ckptPath, "a+");
    if (!ckptFile) die("cannot open checkpoint %s: %s", ckptPath, strerror(errno));
    if (flock(fileno(ckptFile), LOCK_EX | LOCK_NB) != 0)
        die("checkpoint %s is locked by another running instance", ckptPath);
    rewind(ckptFile);
    char line[512];
    int loaded = 0;
    bool haveHeader = false, endsWithNewline = true;
    while (fgets(line, sizeof line, ckptFile)) {
        size_t len = strlen(line);
        endsWithNewline = len > 0 && line[len - 1] == '\n';
        if (!haveHeader) {
            line[strcspn(line, "\r\n")] = 0;
            if (strcmp(line, want) != 0)
                die("checkpoint %s belongs to a different run:\n  file: %s\n  want: %s", ckptPath, line, want);
            haveHeader = true;
            continue;
        }
        if (line[0] != 'U' || !endsWithNewline) continue;     /* comment or torn line */
        int x, y, wgt;
        char cnt[64];
        double secs;
        if (sscanf(line, "U %d %d %d %63s %lf", &x, &y, &wgt, cnt, &secs) != 5) continue;
        u128 c;
        if (x < 0 || x >= nR || y < 0 || y >= nR || !parse_u128(cnt, &c)) continue;
        UnitResult *r = &results[(size_t)x * nR + y];
        if (!r->done) loaded++;
        r->done = true;
        r->count = (uint64_t)c;
        r->secs = secs;
    }
    if (!haveHeader) {
        fprintf(ckptFile, "%s\n", want);
        fprintf(ckptFile, "# U <x> <y> <orbit weight> <count for seam (x,y)> <seconds>\n");
    } else if (!endsWithNewline) {
        fprintf(ckptFile, "\n");                             /* isolate a torn last line */
    }
    fflush(ckptFile);
    fsync(fileno(ckptFile));
    return loaded;
}

static void ckpt_append(const Unit *u, uint64_t count, double secs)
{
    if (!ckptFile) return;
    fprintf(ckptFile, "U %d %d %d %" PRIu64 " %.3f\n", u->x, u->y, u->weight, count, secs);
    fflush(ckptFile);
    fsync(fileno(ckptFile));
}

/* ------------------------------------------------------------------------ */
/* scheduling, progress, main                                               */
/* ------------------------------------------------------------------------ */

static int *order;                    /* pending units, largest cost first  */
static int nOrder;
static _Atomic int nextOrder = 0;
static double costTotal, costDoneStart, costDone;
static int unitsDone;
static u128 partialSum;
static u128 sessionPairMass;
static int nWorkers;
static Worker *workers;
static bool quiet = false;

static void *worker_main(void *arg)
{
    Worker *w = arg;
    for (;;) {
        if (stopRequested) break;
        int oi = atomic_fetch_add(&nextOrder, 1);
        if (oi >= nOrder) break;
        int ui = order[oi];
        const Unit *u = &units[ui];
        atomic_store(&w->progPpm, 0);
        atomic_store(&w->curUnit, ui);
        double t0 = now_sec();
        uint64_t cnt = 0;
        u128 massBefore = w->pairMass;
        bool ok = run_unit(w, u, &cnt);
        double dt = now_sec() - t0;
        atomic_store(&w->curUnit, -1);
        if (!ok) break;
        pthread_mutex_lock(&lock);
        UnitResult *r = &results[(size_t)u->x * nR + u->y];
        r->done = true;
        r->count = cnt;
        r->secs = dt;
        ckpt_append(u, cnt, dt);
        costDone += u->cost;
        unitsDone++;
        partialSum += (u128)cnt * (u128)u->weight;
        sessionPairMass += (w->pairMass - massBefore) * (u128)u->weight;
        pthread_mutex_unlock(&lock);
    }
    return NULL;
}

static void on_signal(int sig)
{
    (void)sig;
    if (stopRequested) _exit(130);
    stopRequested = 1;
    const char msg[] = "\n[interrupt] finishing checkpoint and stopping (Ctrl-C again to abort immediately)\n";
    ssize_t rc = write(2, msg, sizeof msg - 1);
    (void)rc;
}

static void print_progress(double t0, bool final)
{
    pthread_mutex_lock(&lock);
    double cd = costDone;
    int ud = unitsDone;
    u128 ps = partialSum;
    pthread_mutex_unlock(&lock);
    double inprog = 0;
    int active = 0;
    for (int i = 0; i < nWorkers; i++) {
        int ui = atomic_load(&workers[i].curUnit);
        if (ui >= 0) {
            active++;
            inprog += units[ui].cost * (double)atomic_load(&workers[i].progPpm) / 1e6;
        }
    }
    double el = now_sec() - t0;
    double doneNow = cd + inprog;
    double frac = costTotal > 0 ? doneNow / costTotal : 1;
    double sess = doneNow - costDoneStart;
    double eta = sess > 0 ? (costTotal - doneNow) * el / sess : -1;
    char e1[32], e2[32], ps_s[48];
    fmt_dur(el, e1, sizeof e1);
    fmt_dur(eta, e2, sizeof e2);
    u128_str(ps, ps_s);
    time_t tt = time(NULL);
    struct tm tmv;
    localtime_r(&tt, &tmv);
    char ts[32];
    strftime(ts, sizeof ts, "%H:%M:%S", &tmv);
    char etaAt[32] = "";
    if (eta >= 0 && !final) {
        time_t fin = tt + (time_t)eta;
        struct tm tf;
        localtime_r(&fin, &tf);
        strftime(etaAt, sizeof etaAt, " (~%a %H:%M)", &tf);
    }
    fprintf(stderr, "[%s] units %d/%d  work %6.2f%%  active %d  elapsed %s  ETA %s%s  partial %s\n",
            ts, ud, nUnits, 100.0 * frac, active, e1, final ? "-" : e2, etaAt, ps_s);
}

static void usage(const char *prog)
{
    fprintf(stderr,
        "usage: %s [options]\n"
        "  -n N        half size: count 2N x 2N grids (1..6, default 6)\n"
        "  -t T        worker threads (default: all %d CPUs)\n"
        "  -c FILE     checkpoint file (default: a253316_n<N>.ckpt)\n"
        "  -p SEC      progress report interval in seconds (default 10)\n"
        "  -m GB       memory budget for half-grid buffers (default: 50%% of RAM)\n"
        "  --no-checkpoint   do not read or write a checkpoint file\n"
        "  --no-symmetry     process every seam (slower; for cross-checking)\n"
        "  --selftest        verify against brute force and the known terms n=1..5\n"
        "  --check-orbits K  recount all seams of K random symmetry orbits (consistency check)\n"
        "  --bench K         time K sample work units single-threaded\n"
        "  --unit X Y        time the single work unit with seam rows X, Y\n"
        "  --join M          pair counting method: auto (default), bitset, ie, or\n"
        "                    brute (check every candidate pair; slow reference)\n"
        "  --ie-min X        auto: use inclusion-exclusion when A*B > X*(A+B) (default 6400)\n"
        "  -q          quiet (only the result line)\n",
        prog, ncpu());
}

/* straightforward backtracking count, used only by --selftest (n <= 4) */
static uint32_t bfRows[MAXC];
static int bfCnt[MAXC];
static uint64_t bfTotal;

static void brute(int k)
{
    uint32_t mask = (1u << N) - 1;
    if (k == N) {
        for (int i = 0; i < N; i++)
            for (int j = i + 1; j < N; j++) if (bfRows[i] == bfRows[j]) return;
        uint32_t col[MAXC];
        for (int j = 0; j < N; j++) {
            col[j] = 0;
            for (int i = 0; i < N; i++) col[j] |= ((bfRows[i] >> j) & 1u) << i;
        }
        for (int i = 0; i < N; i++)
            for (int j = i + 1; j < N; j++) if (col[i] == col[j]) return;
        bfTotal++;
        return;
    }
    for (int r = 0; r < nR; r++) {
        uint32_t x = lineBits[r];
        if (k >= 2 && (~(bfRows[k - 2] ^ bfRows[k - 1]) & ~(bfRows[k - 1] ^ x) & mask)) continue;
        bool ok = true;
        for (int j = 0; j < N && ok; j++) {
            int c = bfCnt[j] + (int)((x >> j) & 1);
            if (c > n || c + (N - 1 - k) < n) ok = false;
        }
        if (!ok) continue;
        for (int j = 0; j < N; j++) bfCnt[j] += (x >> j) & 1;
        bfRows[k] = x;
        brute(k + 1);
        for (int j = 0; j < N; j++) bfCnt[j] -= (x >> j) & 1;
    }
}

/* full computation for the current tables; returns the total */
static u128 compute(int threads, bool useSym, bool useCkpt, double progressSec, bool isSelftest)
{
    build_units(useSym);
    results = calloc((size_t)nR * nR, sizeof *results);
    if (!results) die("out of memory");

    int loaded = 0;
    if (useCkpt) {
        loaded = ckpt_init(useSym);
    }

    qsort(units, (size_t)nUnits, sizeof *units, cmp_unit_cost_desc);
    order = xmalloc((size_t)nUnits * sizeof *order);
    nOrder = 0;
    costTotal = costDone = 0;
    unitsDone = 0;
    partialSum = 0;
    sessionPairMass = 0;
    for (int i = 0; i < nUnits; i++) {
        costTotal += units[i].cost;
        UnitResult *r = &results[(size_t)units[i].x * nR + units[i].y];
        if (r->done) {
            costDone += units[i].cost;
            unitsDone++;
            partialSum += (u128)r->count * (u128)units[i].weight;
        } else order[nOrder++] = i;
    }
    costDoneStart = costDone;
    atomic_store(&nextOrder, 0);

    if (!quiet && !isSelftest) {
        fprintf(stderr, "A253316: counting %dx%d Takuzu grids (n=%d)\n", N, N, n);
        fprintf(stderr, "  valid lines: %d   seams: %d   work units after symmetry: %d\n",
                nR, nR * (nR - 1), nUnits);
        fprintf(stderr, "  threads: %d   memory budget: %.1f GB   checkpoint: %s\n", threads,
                (double)memBudgetPerThread * threads / 1073741824.0, useCkpt ? ckptPath : "(none)");
        if (loaded) fprintf(stderr, "  resumed: %d units already done (%.2f%% of estimated work)\n",
                            loaded, 100.0 * costDone / costTotal);
    }

    nWorkers = threads;
    workers = xmalloc((size_t)threads * sizeof *workers);
    pthread_t *tids = xmalloc((size_t)threads * sizeof *tids);
    double t0 = now_sec();
    for (int i = 0; i < threads; i++) {
        worker_init(&workers[i], i);
        pthread_attr_t attr;
        pthread_attr_init(&attr);
        pthread_attr_setstacksize(&attr, 16u << 20);
        if (pthread_create(&tids[i], &attr, worker_main, &workers[i]) != 0) die("pthread_create failed");
        pthread_attr_destroy(&attr);
    }

    double lastReport = t0;
    for (;;) {
        bool anyRunning = false;
        /* all workers finished when every pending unit is taken and none is active */
        if (atomic_load(&nextOrder) >= nOrder || stopRequested) {
            anyRunning = false;
            for (int i = 0; i < threads; i++) if (atomic_load(&workers[i].curUnit) >= 0) anyRunning = true;
            if (!anyRunning) break;
        }
        usleep(100000);
        double t = now_sec();
        if (!quiet && !isSelftest && progressSec > 0 && t - lastReport >= progressSec) {
            print_progress(t0, false);
            lastReport = t;
        }
    }
    for (int i = 0; i < threads; i++) pthread_join(tids[i], NULL);
    double el = now_sec() - t0;

    u128 total = 0;
    int missing = 0;
    for (int i = 0; i < nUnits; i++) {
        UnitResult *r = &results[(size_t)units[i].x * nR + units[i].y];
        if (!r->done) { missing++; continue; }
        total += (u128)r->count * (u128)units[i].weight;
    }
    if (!quiet && !isSelftest) {
        print_progress(t0, true);
        char pm[48];
        fprintf(stderr, "  session time %.1fs; candidate pairs examined this session (weighted): %s\n",
                el, u128_str(sessionPairMass, pm));
    }
    for (int i = 0; i < threads; i++) worker_free(&workers[i]);
    free(workers);
    free(tids);
    free(order);
    if (ckptFile) {
        if (missing == 0 && nOrder > 0) {           /* this session finished the run */
            char buf[48];
            fprintf(ckptFile, "# RESULT a(%d) = %s\n", n, u128_str(total, buf));
            fflush(ckptFile);
        }
        fclose(ckptFile);
        ckptFile = NULL;
    }
    free(results);
    results = NULL;
    free(units);
    units = NULL;
    free(halfCnt);
    halfCnt = NULL;
    free(adjStart);
    free(adjList);
    if (missing) {
        if (!quiet && !isSelftest)
            fprintf(stderr, "stopped with %d of %d units remaining; rerun the same command to resume.\n",
                    missing, nUnits);
        return (u128)-1;
    }
    return total;
}

/* time single units (one thread) at spread-out positions of the cost ranking */
static void bench(int samples, int onlyX, int onlyY)
{
    build_units(true);
    qsort(units, (size_t)nUnits, sizeof *units, cmp_unit_cost_desc);
    Worker *w = xmalloc(sizeof *w);
    worker_init(w, 0);
    double costAll = 0;
    for (int i = 0; i < nUnits; i++) costAll += units[i].cost;
    fprintf(stderr, "%5s %4s %4s %2s %10s %10s %8s %8s %6s %14s %13s %6s %6s %7s %8s %10s\n", "rank", "x", "y", "wt",
            "halvesT", "halvesB", "estT", "estB", "groups", "pairMass", "count", "enum", "sort", "join", "total", "sec/cost");
    double sumRatio = 0;
    int cnt = 0;
    for (int s = 0; s < samples; s++) {
        int i;
        if (onlyX >= 0) {
            for (i = 0; i < nUnits; i++) if (units[i].x == onlyX && units[i].y == onlyY) break;
            if (i == nUnits) die("(%d,%d) is not a canonical seam", onlyX, onlyY);
        } else {
            /* geometric spread over ranks */
            double f = samples > 1 ? (double)s / (samples - 1) : 0;
            i = (int)(pow((double)nUnits, f)) - 1;
            if (i < 0) i = 0;
            if (i >= nUnits) i = nUnits - 1;
        }
        const Unit *u = &units[i];
        w->nHalfT = w->nHalfB = w->nGroups = 0;
        w->pairMass = 0;
        w->tEnum = w->tSort = w->tJoin = 0;
        uint64_t c = 0;
        double t0 = now_sec();
        run_unit(w, u, &c);
        double dt = now_sec() - t0;
        char pm[48];
        double ratio = dt / u->cost;
        sumRatio += ratio;
        cnt++;
        fprintf(stderr, "%5d %4d %4d %2d %10" PRIu64 " %10" PRIu64 " %8.3g %8.3g %6" PRIu64 " %14s %13" PRIu64
                " %6.2f %6.2f %7.2f %8.2f %10.3g\n", i, u->x, u->y, u->weight, w->nHalfT, w->nHalfB, u->estT, u->estB,
                w->nGroups, u128_str(w->pairMass, pm), c, w->tEnum, w->tSort, w->tJoin, dt, ratio);
        if (onlyX >= 0) break;
    }
    if (cnt) fprintf(stderr, "mean sec/cost %.3g -> single-thread estimate for all units: %.0f s\n",
                     sumRatio / cnt, sumRatio / cnt * costAll);
    worker_free(w);
    free(w);
}

/* --check-orbits: recount every seam of some random orbits; all must agree */
typedef struct {
    Unit *jobs;
    uint64_t *counts;
    int njobs;
    _Atomic int next;
} JobList;

static void *job_main(void *arg)
{
    void **a = arg;
    JobList *jl = a[0];
    Worker *w = a[1];
    for (;;) {
        int j = atomic_fetch_add(&jl->next, 1);
        if (j >= jl->njobs || stopRequested) break;
        run_unit(w, &jl->jobs[j], &jl->counts[j]);
    }
    return NULL;
}

static int check_orbits(int samples, int threads)
{
    uint32_t mask = (1u << N) - 1;
    build_units(true);
    qsort(units, (size_t)nUnits, sizeof *units, cmp_unit_cost_desc);
    JobList jl = { xmalloc((size_t)samples * 8 * sizeof(Unit)), xmalloc((size_t)samples * 8 * sizeof(uint64_t)), 0, 0 };
    int *owner = xmalloc((size_t)samples * 8 * sizeof(int));
    uint64_t rng = 0x243F6A8885A308D3ull;
    for (int s = 0; s < samples; s++) {
        rng = rng * 6364136223846793005ull + 1442695040888963407ull;
        int ui = nUnits / 4 + (int)((rng >> 33) % (uint64_t)(nUnits - nUnits / 4));
        const Unit *u = &units[ui];
        int x = u->x, y = u->y;
        int gx[4] = { x, lineCompl[x], lineRev[x], lineRev[lineCompl[x]] };
        int gy[4] = { y, lineCompl[y], lineRev[y], lineRev[lineCompl[y]] };
        int img[8][2], m = 0;
        for (int g = 0; g < 4; g++) {
            int cand[2][2] = { { gx[g], gy[g] }, { gy[g], gx[g] } };
            for (int c = 0; c < 2; c++) {
                bool dup = false;
                for (int i = 0; i < m; i++) if (img[i][0] == cand[c][0] && img[i][1] == cand[c][1]) dup = true;
                if (!dup) { img[m][0] = cand[c][0]; img[m][1] = cand[c][1]; m++; }
            }
        }
        if (m != u->weight) die("internal: orbit size %d != weight %d", m, u->weight);
        for (int i = 0; i < m; i++) {
            Unit v = *u;
            v.x = img[i][0];
            v.y = img[i][1];
            uint32_t D = ~(lineBits[v.x] ^ lineBits[v.y]) & mask;
            v.estT = est_half(v.x, D);
            v.estB = est_half(v.y, D);
            owner[jl.njobs] = s;
            jl.jobs[jl.njobs++] = v;
        }
    }
    Worker *ws = xmalloc((size_t)threads * sizeof *ws);
    pthread_t *tids = xmalloc((size_t)threads * sizeof *tids);
    void *args[64][2];
    if (threads > 64) threads = 64;
    for (int i = 0; i < threads; i++) {
        worker_init(&ws[i], i);
        args[i][0] = &jl;
        args[i][1] = &ws[i];
        pthread_create(&tids[i], NULL, job_main, args[i]);
    }
    for (int i = 0; i < threads; i++) pthread_join(tids[i], NULL);
    int bad = 0;
    for (int s = 0, j = 0; s < samples; s++) {
        int j0 = j;
        bool same = true;
        while (j < jl.njobs && owner[j] == s) { if (jl.counts[j] != jl.counts[j0]) same = false; j++; }
        fprintf(stderr, "  orbit of seam (%3d,%3d): %d seams, count %" PRIu64 " %s\n", jl.jobs[j0].x, jl.jobs[j0].y,
                j - j0, jl.counts[j0], same ? "all equal" : "MISMATCH");
        if (!same) {
            bad++;
            for (int k = j0; k < j; k++)
                fprintf(stderr, "      (%3d,%3d) -> %" PRIu64 "\n", jl.jobs[k].x, jl.jobs[k].y, jl.counts[k]);
        }
    }
    for (int i = 0; i < threads; i++) worker_free(&ws[i]);
    fprintf(stderr, bad ? "orbit check FAILED\n" : "orbit check passed\n");
    return bad ? 1 : 0;
}

static int selftest(int threads)
{
    int fails = 0;
    fprintf(stderr, "self-test: brute force (n<=4) and known OEIS terms (n<=5)\n");
    for (int k = 1; k <= 5; k++) {
        init_tables(k);
        compute_half_counts();
        uint64_t bf = 0;
        bool haveBf = false;
        if (k <= 4) {
            bfTotal = 0;
            memset(bfCnt, 0, sizeof bfCnt);
            brute(0);
            bf = bfTotal;
            haveBf = true;
        }
        double t0 = now_sec();
        u128 symRes = compute(threads, true, false, 0, true);
        double t1 = now_sec();
        init_tables(k);
        compute_half_counts();
        u128 fullRes = compute(threads, false, false, 0, true);
        double t2 = now_sec();
        char a[48], b[48], bfs[32];
        u128_str(symRes, a);
        u128_str(fullRes, b);
        if (haveBf) snprintf(bfs, sizeof bfs, "%" PRIu64, bf);
        else snprintf(bfs, sizeof bfs, "-");
        bool ok = strcmp(a, KNOWN[k]) == 0 && strcmp(b, KNOWN[k]) == 0 && (!haveBf || bf == (uint64_t)symRes);
        fprintf(stderr, "  n=%d %2dx%-2d  symmetric %-12s (%6.2fs)  all seams %-12s (%6.2fs)  brute force %-8s  OEIS %-12s %s\n",
                k, 2 * k, 2 * k, a, t1 - t0, b, t2 - t1, bfs, KNOWN[k], ok ? "OK" : "FAIL");
        if (!ok) fails++;
    }
    fprintf(stderr, fails ? "self-test FAILED\n" : "self-test passed\n");
    return fails ? 1 : 0;
}

int main(int argc, char **argv)
{
    int half = 6, threads = ncpu();
    double progressSec = 10, memGB = physmem_gb() * 0.5;
    bool useCkpt = true, useSym = true, doSelftest = false;
    int benchSamples = 0, unitX = -1, unitY = -1, orbitSamples = 0;
    const char *ck = NULL;

    for (int i = 1; i < argc; i++) {
        const char *a = argv[i];
        if (!strcmp(a, "-n") && i + 1 < argc) half = atoi(argv[++i]);
        else if (!strcmp(a, "-t") && i + 1 < argc) threads = atoi(argv[++i]);
        else if (!strcmp(a, "-c") && i + 1 < argc) ck = argv[++i];
        else if (!strcmp(a, "-p") && i + 1 < argc) progressSec = atof(argv[++i]);
        else if (!strcmp(a, "-m") && i + 1 < argc) memGB = atof(argv[++i]);
        else if (!strcmp(a, "--no-checkpoint")) useCkpt = false;
        else if (!strcmp(a, "--no-symmetry")) useSym = false;
        else if (!strcmp(a, "--selftest")) doSelftest = true;
        else if (!strcmp(a, "--bench") && i + 1 < argc) benchSamples = atoi(argv[++i]);
        else if (!strcmp(a, "--check-orbits") && i + 1 < argc) orbitSamples = atoi(argv[++i]);
        else if (!strcmp(a, "--ie-min") && i + 1 < argc) ieMin = atof(argv[++i]);
        else if (!strcmp(a, "--join") && i + 1 < argc) {
            const char *m = argv[++i];
            if (!strcmp(m, "auto")) joinMode = JOIN_AUTO;
            else if (!strcmp(m, "bitset")) joinMode = JOIN_BITSET;
            else if (!strcmp(m, "ie")) joinMode = JOIN_IE;
            else if (!strcmp(m, "brute")) joinMode = JOIN_BRUTE;
            else { usage(argv[0]); return 2; }
        }
        else if (!strcmp(a, "--unit") && i + 2 < argc) { unitX = atoi(argv[++i]); unitY = atoi(argv[++i]); }
        else if (!strcmp(a, "-q")) quiet = true;
        else if (!strcmp(a, "-h") || !strcmp(a, "--help")) { usage(argv[0]); return 0; }
        else { usage(argv[0]); return 2; }
    }
    if (threads < 1) threads = 1;
    if (memGB < 0.001) memGB = 0.001;
    memBudgetPerThread = (size_t)(memGB * 1073741824.0 / threads);

    signal(SIGINT, on_signal);
    signal(SIGTERM, on_signal);

    if (doSelftest) return selftest(threads);

    if (half == 0) { printf("a(0) = 1\n"); return 0; }
    if (half < 1 || half > MAXN) die("n must be between 0 and %d", MAXN);
    if (ck) snprintf(ckptPath, sizeof ckptPath, "%s", ck);
    else snprintf(ckptPath, sizeof ckptPath, "a253316_n%d.ckpt", half);

    init_tables(half);
    compute_half_counts();
    if (orbitSamples > 0) return check_orbits(orbitSamples, threads);
    if (benchSamples > 0 || unitX >= 0) {
        bench(unitX >= 0 ? 1 : benchSamples, unitX, unitY);
        return 0;
    }
    u128 res = compute(threads, useSym, useCkpt, progressSec, false);
    if (res == (u128)-1) return 3;
    char buf[48];
    printf("a(%d) = %s\n", half, u128_str(res, buf));
    if (half < NKNOWN) {
        bool ok = strcmp(buf, KNOWN[half]) == 0;
        if (!quiet) fprintf(stderr, "%s known value %s\n", ok ? "matches" : "DOES NOT MATCH", KNOWN[half]);
        return ok ? 0 : 4;
    }
    return 0;
}
