/*
 * a034822.c -- exhaustive search for palindromic squares of a given length L
 *
 * OEIS A034822: numbers k such that there are no palindromic squares of
 * length k.  Known: 2,4,8,10,14,18,20,24,30,38,40,46,54,56,62,64.  All lengths
 * <= 69 have been searched exhaustively (De Geest / R. Xiao, CUDA; the single
 * 68-digit square 7256171055736382499839982033184475^2 was found 2025-04-14),
 * so the next candidate term is L = 70.  All terms are even (odd lengths
 * always contain (10^k+1)^2), so only even L matter; the tool works for any L.
 *
 * Method (two-ended digit matching, ~10^(L/4) work):
 *
 *   Let D = ceil(L/2) (digits of the root n), and fix h ~ D/2.  Write
 *   n = t*10^h + B with 0 <= B < 10^h.  B determines the low h digits of
 *   S = n^2 (namely B^2 mod 10^h); if S is a palindrome these fix the high h
 *   digits P of S, so S lies in [P*10^(L-h), (P+1)*10^(L-h)) and hence
 *
 *        isqrt(P*10^e) <= t <= isqrt((P+1)*10^e),     e = L - 3h.
 *
 *   That window holds ~10^(D-2h) values of t, i.e. O(1) for h ~ D/2.  So the
 *   search enumerates B (the low half of the root), computes P by reversing
 *   the low digits of B^2, takes two 128-bit integer square roots, and tests
 *   the few t in the window.
 *
 *   Savings:
 *    - B and B + 5*10^(h-1), and their negatives mod 10^h, have the same
 *      square mod 10^h (h >= 2), so one window serves 4 roots; B enumerates
 *      unit digit 1..5 and top digit 0..4 (unit 5: tens digit 0..4 as well).
 *    - n = 0 (mod 10) is impossible (S would end in 0).
 *    - even L: every even-length palindrome is divisible by 11, hence
 *      11 | n, so t runs through a single class mod 11 (step 11).
 *
 *   Per candidate: digits h and h+1 of S come from C = 2tB + floor(B^2/10^h)
 *   mod 100, and the top h+2 digits are floor((t^2 + floor(C/10^h))/10^(e-2))
 *   -- only 64x64->128 products and quotients that fit in 64 bits (done with a
 *   double estimate plus exact correction, since arm64 has no 128/64 divide).
 *   Survivors (1 in 100) get a full decimal palindrome check.
 *
 *   The digits of B are generated by a DFS keeping Q_i = floor(B_i^2 / 10^i)
 *   (< 10^i, a u64), which yields S digit i as (Q_i + 2 d B_i + d^2 10^i) mod 10.
 *
 * Work is split into tasks = the low p digits of B (unit digit + p-1 digits),
 * handed out by an atomic counter to pthreads.  A checkpoint file stores the
 * completed-task bitmap so long runs resume.
 *
 * Usage:
 *   a034822 search L [-t threads] [-h H] [-p P] [-S state] [-i secs] [-r a:b]
 *   a034822 selftest [maxL]     compare counts with A263618 for L = 11..maxL
 *   a034822 check n             is n^2 a palindrome?
 *
 * Results: one line "FOUND L n n^2" per palindromic square on stdout,
 * final "DONE L count ..." line; status on stderr.
 */
#include <inttypes.h>
#include <math.h>
#include <pthread.h>
#include <signal.h>
#include <stdatomic.h>
#include <stdint.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <unistd.h>

typedef uint64_t u64;
typedef int64_t i64;
typedef unsigned __int128 u128;
typedef __int128 i128;

static u64 POW10[20];

/* A263618 (number of palindromic squares with n digits), n = 1..69;
 * n = 68, 69 from De Geest's table (Nov 2025). */
static const int KNOWN[70] = {0,
    4,0,3,0,7,1,5,0,11,0,5,1,19,0,13,1,25,0,18,0,48,1,31,0,70,1,44,2,105,
    0,70,1,153,1,98,3,209,0,132,0,291,1,181,1,384,0,234,2,496,1,301,1,
    636,0,383,0,798,1,474,1,981,0,578,0,1199,2,701,1,1443};

/* ---------- 128-bit helpers (no 128/64 hardware divide on arm64) ---------- */

static inline double u128_to_double(u128 x)
{
    return (double)(u64)(x >> 64) * 18446744073709551616.0 + (double)(u64)x;
}

/* floor(x / d), caller guarantees the quotient fits in 64 bits */
static inline u64 udiv128_64(u128 x, u64 d)
{
    double qd = u128_to_double(x) / (double)d;
    u64 q = qd >= 18446744073709549568.0 ? UINT64_MAX : (u64)qd;
    i128 r = (i128)(x - (u128)q * d);
    /* |r| <= ~2^13 * d: one more estimate brings it to within +-1 */
    double rd = r < 0 ? -u128_to_double((u128)(-r)) : u128_to_double((u128)r);
    i64 adj = (i64)(rd / (double)d);
    q += (u64)adj;
    r -= (i128)adj * (i128)d;
    while (r < 0) { q--; r += d; }
    while (r >= (i128)d) { q++; r -= d; }
    return q;
}

/* floor(sqrt(x)) for x < 2^127 */
static inline u64 isqrt128(u128 x)
{
    if (x == 0) return 0;
    u64 r = (u64)sqrt(u128_to_double(x));
    if (r == 0) r = 1;
    /* one Newton step from a ~1e-16 relative estimate */
    u128 s = ((u128)r + udiv128_64(x, r)) >> 1;
    r = (u64)s;
    while ((u128)r * r > x) r--;
    while ((u128)(r + 1) * (r + 1) <= x) r++;
    return r;
}

/* ---------- full palindrome check of n^2, n < 10^37 ---------- */

static int square_digits(u128 n, char *out) /* returns number of digits */
{
    u64 a[6] = {0}, s[12] = {0};
    int na = 0;
    while (n) { a[na++] = (u64)(n % 1000000000u); n /= 1000000000u; }
    for (int i = 0; i < na; i++) {
        u64 carry = 0;
        for (int j = 0; j < na; j++) {
            u64 v = s[i + j] + a[i] * a[j] + carry;
            s[i + j] = v % 1000000000u;
            carry = v / 1000000000u;
        }
        int k = i + na;
        while (carry) { u64 v = s[k] + carry; s[k] = v % 1000000000u; carry = v / 1000000000u; k++; }
    }
    int ns = 2 * na;
    while (ns > 0 && s[ns - 1] == 0) ns--;
    char buf[128];
    int len = 0;
    for (int i = 0; i < ns; i++) {
        u64 v = s[i];
        for (int k = 0; k < 9; k++) { buf[len++] = (char)('0' + v % 10); v /= 10; }
    }
    while (len > 1 && buf[len - 1] == '0') len--;
    for (int i = 0; i < len; i++) out[i] = buf[len - 1 - i];
    out[len] = 0;
    return len;
}

static int is_pal(const char *s, int len)
{
    for (int i = 0, j = len - 1; i < j; i++, j--)
        if (s[i] != s[j]) return 0;
    return 1;
}

static void u128_str(u128 n, char *out)
{
    char buf[64];
    int len = 0;
    do { buf[len++] = (char)('0' + (int)(n % 10)); n /= 10; } while (n);
    for (int i = 0; i < len; i++) out[i] = buf[len - 1 - i];
    out[len] = 0;
}

static int parse_u128(const char *s, u128 *out)
{
    u128 v = 0;
    if (!*s) return 0;
    for (; *s; s++) {
        if (*s < '0' || *s > '9') return 0;
        v = v * 10 + (u128)(*s - '0');
    }
    *out = v;
    return 1;
}

/* ---------- search parameters and shared state ---------- */

typedef struct {
    int L, D, h, e, x; /* x = number of extra digit pairs checked cheaply (1 or 2) */
    int p;             /* task depth: low p digits of B fixed per task */
    int mod11;         /* even L: 11 | n */
    u64 ntasks;
    u64 pe, pex;       /* 10^e (as needed), 10^(e-x) */
} params_t;

static params_t G;

static pthread_mutex_t out_lock = PTHREAD_MUTEX_INITIALIZER;
static atomic_ullong next_task;
static atomic_ullong found_count, nodes_total, cands_total, pass_total, filt_total;
static unsigned char *done_map; /* 1 byte per task */
static u64 task_lo, task_hi;
static volatile sig_atomic_t stop_flag = 0;
static int quiet = 0;

/* Found squares collected for selftest */
#define MAXFOUND 4096
static u128 found_list[MAXFOUND];

typedef struct {
    u64 nodes, cands, filt, pass, pass3, found;
} stats_t;

static void report(u128 n)
{
    char ns[64], ss[128];
    u128_str(n, ns);
    int len = square_digits(n, ss);
    pthread_mutex_lock(&out_lock);
    u64 k = atomic_fetch_add(&found_count, 1);
    if (k < MAXFOUND) found_list[k] = n;
    if (!quiet) {
        printf("FOUND %d %s %s\n", len, ns, ss);
        fflush(stdout);
    }
    pthread_mutex_unlock(&out_lock);
}

/* Window base for a DFS subtree: every leaf below has P in [Pb, Pb + 10^(h-ib)),
 * and sqrt(P*10^e) = Rb + v(u), u = P - Pb, with
 * v(u) = frac + u*s1 - u^2*s2 (cubic remainder < 1e-7 by choice of ib). */
typedef struct {
    u64 Pb, Rb;
    double frac, s1, s2;
} base_t;

static int IB;          /* depth at which the base is computed */
static double EPS = 1e-5;
#define SLACK 64        /* filter slack for the fixed-point top-digit estimate */

static void make_base(u64 Pb, base_t *b)
{
    u128 X = (u128)Pb * G.pe;
    u64 r = isqrt128(X);
    double R = (double)r;
    b->Pb = Pb;
    b->Rb = r;
    b->frac = u128_to_double(X - (u128)r * r) / (2.0 * R + 1e-300);
    double Rreal = R + b->frac, Pd = (double)Pb;
    b->s1 = Rreal / (2.0 * Pd);
    b->s2 = Rreal / (8.0 * Pd * Pd);
}

static inline u64 umulh(u64 a, u64 b) { return (u64)(((u128)a * b) >> 64); }

/* exact test of candidate t for root Bp (Bq = floor(Bp^2/10^h)) */
static inline int exact_top_ok(u64 t, u64 Bp, u64 Bq, u64 want)
{
    u128 C = (u128)2 * t * Bp + Bq;
    u64 X = udiv128_64(C, POW10[G.h]);
    u128 Y = (u128)t * t + X;
    return udiv128_64(Y, G.pex) == want;
}

static u64 H5, Q25, H5M11, PHM11; /* 5*10^(h-1), 25*10^(h-2), and their residues mod 11 */
static unsigned char REV2[100];    /* REV2[10a+b] = 10b+a */

/* Test one candidate t for root Bp: the cheap filter on S digits h, h+1 vs
 * L-1-h, L-2-h, then the exact check, then the full palindrome test.
 * W0 = P*10^e; low2 = (floor(Bp^2/10^h) + 2 t Bp) mod 100. */
static inline void test_cand(u64 t, u64 Bp, u64 Bq, u64 f, u64 P, u128 W0, u64 low2, stats_t *st)
{
    u64 y = (G.x == 2) ? REV2[low2] : low2 % 10;
    u128 W = W0 + (u128)y * G.pex;
    u128 V = (u128)t * t + umulh(2 * t, f);
#ifdef PARANOID
    {
        u64 want = P * POW10[G.x] + y;
        int ex = exact_top_ok(t, Bp, Bq, want);
        int fl = (V + SLACK >= W && V < W + G.pex + SLACK);
        if (ex && !fl) { fprintf(stderr, "PARANOID: filter rejected exact hit t=%llu B=%llu\n",
                                 (unsigned long long)t, (unsigned long long)Bp); abort(); }
    }
#endif
    if (__builtin_expect(V + SLACK < W || V >= W + G.pex + SLACK, 1)) return;
    /* exact: S = Y*10^(2h) + c0*10^h + (Bp^2 mod 10^h) */
    const int h = G.h, L = G.L;
    u128 C = (u128)2 * t * Bp + Bq;
    u64 X = udiv128_64(C, POW10[h]);
    u64 c0 = (u64)(C - (u128)X * POW10[h]);
    u128 Y = (u128)t * t + X;
    if (udiv128_64(Y, G.pex) != P * POW10[G.x] + y) return;
    st->pass++;
    /* S digit p (h <= p < 2h, in c0) mirrors S digit L-1-p = Y digit L-1-p-2h */
    {
        u64 yq = udiv128_64(Y, 10000000000000000000ull);
        u64 Ym = (u64)(Y - (u128)yq * 10000000000000000000ull);
        int pmax = 2 * h - 1;
        if (pmax > L - 1 - 2 * h) pmax = L - 1 - 2 * h;
        for (int p = h + G.x; p <= pmax; p++) {
            int q = L - 1 - p - 2 * h;
            if (q > 18) continue;
            if ((c0 / POW10[p - h]) % 10 != (Ym / POW10[q]) % 10) return;
        }
    }
    st->pass3++;
    (void)0;
    u128 n = (u128)t * POW10[G.h] + Bp;
    char ss[128];
    int len = square_digits(n, ss);
    if (len == G.L && is_pal(ss, len)) { st->found++; report(n); }
}

/* All candidates t in [tlo, thi] for one root; t0 = first t >= tlo in the root's
 * class mod 11 (or tlo), step 11 (or 1). */
static inline void do_root(u64 Bp, u64 Bq, u64 f, u64 b100, u64 q100, u64 P, u128 W0,
                           u64 t0, u64 thi, u64 step, stats_t *st)
{
#ifdef NOROOT
    st->cands += Bp + Bq + f + b100 + q100 + P + (u64)W0 + t0 + thi + step; return;
#endif
    u64 tm = t0 % 100;
    u64 low2 = (q100 + 2 * b100 * tm) % 100;
    u64 dlow = (2 * b100 * step) % 100;
    for (u64 t = t0; t <= thi; t += step) {
        st->cands++;
        test_cand(t, Bp, Bq, f, P, W0, low2, st);
        low2 += dlow;
        if (low2 >= 100) low2 -= 100;
    }
}

/* Leaf: full B (h digits, unit 1..5, top digit 0..4), P, Q = floor(B^2/10^h),
 * f ~ B*2^64/10^h, b11 = B mod 11. */
static inline void do_leaf(u64 B, u64 P, u64 Q, u64 f, u64 b11, const base_t *bs, stats_t *st)
{
    const int h = G.h;
    st->nodes++;
    double u = (double)(P - bs->Pb);
    double vlo = bs->frac + u * bs->s1 - u * u * bs->s2;
    double u1 = u + 1.0;
    double vhi = bs->frac + u1 * bs->s1 - u1 * u1 * bs->s2;
    i64 a = (i64)floor(vlo - EPS), b = (i64)floor(vhi + EPS);
    u64 tlo = bs->Rb + (u64)a, thi = bs->Rb + (u64)b;
    if (a < 0 && (u64)(-a) > bs->Rb) tlo = 0;
#ifdef PARANOID
    {
        u64 elo = isqrt128((u128)P * G.pe), ehi = isqrt128((u128)(P + 1) * G.pe);
        if (tlo > elo || thi < ehi) {
            fprintf(stderr, "PARANOID: window [%llu,%llu] misses exact [%llu,%llu] P=%llu\n",
                    (unsigned long long)tlo, (unsigned long long)thi, (unsigned long long)elo,
                    (unsigned long long)ehi, (unsigned long long)P);
            abort();
        }
    }
#endif
    u128 W0 = (u128)P * G.pe;
    u64 b100 = B % 100, q100 = Q % 100, nb100 = (100 - b100) % 100;
    /* roots: B, B + H5, 10^h - B, H5 - B; floor(root^2/10^h) mod 100 below
     * (Q25 and 10^h vanish mod 100 for h >= 4; general h handled by % 100). */
    u64 BqA = Q, BqB = Q + B + Q25, BqC = POW10[h] - 2 * B + Q, BqD = Q25 - B + Q;
    u64 rA = b11, rB = (b11 + H5M11) % 11, rC = (PHM11 + 11 - b11) % 11, rD = (H5M11 + 11 - b11) % 11;
    u64 step = 1, tA = tlo, tB = tlo, tC = tlo, tD = tlo;
    if (G.mod11) {
        /* t*10^h + root = 0 (mod 11), 10 = -1 (mod 11): t = -(-1)^h root */
        u64 tm = tlo % 11;
        step = 11;
        if (!(h & 1)) { rA = (11 - rA) % 11; rB = (11 - rB) % 11; rC = (11 - rC) % 11; rD = (11 - rD) % 11; }
        tA = tlo + (rA + 11 - tm) % 11;
        tB = tlo + (rB + 11 - tm) % 11;
        tC = tlo + (rC + 11 - tm) % 11;
        tD = tlo + (rD + 11 - tm) % 11;
    }
    do_root(B, BqA, f, b100, BqA % 100, P, W0, tA, thi, step, st);
    do_root(B + H5, BqB, f + (1ull << 63), b100, BqB % 100, P, W0, tB, thi, step, st);
    do_root(POW10[h] - B, BqC, 0 - f, nb100, BqC % 100, P, W0, tC, thi, step, st);
    do_root(H5 - B, BqD, (1ull << 63) - f, nb100, BqD % 100, P, W0, tD, thi, step, st);
    (void)q100;
}

static int FAST; /* even L, h >= 4, window <= 22: branchless two-candidate path */

static inline u64 addmod(u64 a, u64 b, u64 m) { u64 c = a + b; return c >= m ? c - m : c; }
static inline u64 submod(u64 a, u64 b, u64 m) { return a >= b ? a - b : a + m - b; }

static u64 P4; /* 10^(e-4), 0 if e < 4 or x != 2 */

/* Stage B: four digit pairs.  low4 = S digits h..h+3; the top digits after P
 * are D / 10^(e-4) (4 digits); near a digit boundary defer to the exact test. */
static inline int stageB(u64 t, u64 Bp, u64 Bq, u64 D, stats_t *st)
{
    st->filt++;
    if (!P4) return 1;
    u64 low4 = (Bq % 10000 + 2 * (Bp % 10000) * (t % 10000)) % 10000;
    u64 y4 = D / P4, rem = D - y4 * P4;
    if (rem < SLACK || rem > P4 - SLACK) return 1;
    return y4 == 100u * REV2[low4 % 100] + REV2[low4 / 100];
}

/* Fast path.  D = t^2 + floor(2 t f / 2^64) - P*10^e is the part of
 * floor(S/10^(2h)) below the P prefix; a true hit has D in [y pex, (y+1) pex)
 * with (y+1) pex <= 10^e < 2^64, so D mod 2^64 is exact there and the filter
 * runs in wrapping 64-bit arithmetic (false positives go to the exact test). */
static inline void fast_root(u64 Bp, u64 Bq, u64 f, u64 b100, u64 q100, u64 P, u128 W0, u64 W0lo,
                             u64 tlo, u64 T2, u64 k, u64 tm100, u64 thi, stats_t *st)
{
    const u64 pex = G.pex;
    u64 t0 = tlo + k, t1 = t0 + 11;
    u64 sq0 = T2 + 2 * tlo * k + k * k;
    u64 sq1 = sq0 + 22 * t0 + 121;
    u64 D0 = sq0 + umulh(2 * t0, f) - W0lo;
    u64 D1 = sq1 + umulh(2 * t1, f) - W0lo;
    u64 m = (2 * b100) % 100;
    u64 tt = tm100 + k;
    u64 l0 = (q100 + m * tt) % 100, l1 = (q100 + m * (tt + 11)) % 100;
    u64 y0 = (G.x == 2) ? REV2[l0] : l0 % 10, y1 = (G.x == 2) ? REV2[l1] : l1 % 10;
    int h0 = (t0 <= thi) & (D0 + SLACK - y0 * pex < pex + 2 * SLACK);
    int h1 = (t1 <= thi) & (D1 + SLACK - y1 * pex < pex + 2 * SLACK);
#ifdef PARANOID
    {
        stats_t dummy = {0};
        for (u64 t = t0; t <= thi; t += 11) {
            u64 l = (q100 + m * ((tm100 + (t - tlo)) % 100)) % 100;
            u64 y = (G.x == 2) ? REV2[l] : l % 10;
            u128 W = W0 + (u128)y * pex;
            u128 C = (u128)2 * t * Bp + Bq;
            u64 X = udiv128_64(C, POW10[G.h]);
            u128 Y = (u128)t * t + X;
            int ex = (Y >= W && Y < W + pex);
            if (t > t1) { fprintf(stderr, "PARANOID: window wider than 22\n"); abort(); }
            int fl = (t == t0) ? h0 : h1;
            if (ex && !fl) { fprintf(stderr, "PARANOID: fast filter rejected exact hit\n"); abort(); }
        }
        (void)dummy;
    }
#endif
    if (__builtin_expect(h0 | h1, 0)) {
        if (h0 && stageB(t0, Bp, Bq, D0, st)) test_cand(t0, Bp, Bq, f, P, W0, l0, st);
        if (h1 && stageB(t1, Bp, Bq, D1, st)) test_cand(t1, Bp, Bq, f, P, W0, l1, st);
    }
}

static inline void fast_leaf(u64 B, u64 P, u64 Q, u64 f, u64 b11, const base_t *bs, stats_t *st)
{
    const int h = G.h;
    st->nodes++;
    double u = (double)(P - bs->Pb);
    double vlo = bs->frac + u * bs->s1 - u * u * bs->s2;
    double u1 = u + 1.0;
    double vhi = bs->frac + u1 * bs->s1 - u1 * u1 * bs->s2;
    u64 tlo = bs->Rb + (u64)(i64)floor(vlo - EPS), thi = bs->Rb + (u64)(i64)floor(vhi + EPS);
#ifdef PARANOID
    {
        u64 elo = isqrt128((u128)P * G.pe), ehi = isqrt128((u128)(P + 1) * G.pe);
        if (tlo > elo || thi < ehi) { fprintf(stderr, "PARANOID: fast window\n"); abort(); }
    }
#endif
    st->cands += thi - tlo + 1; /* window size (candidates ~ 4/11 of this) */
    u128 W0 = (u128)P * G.pe;
    u64 W0lo = (u64)W0, T2 = tlo * tlo;
    u64 b100 = B % 100, nb100 = submod(0, b100, 100);
    u64 q100 = Q % 100;
    /* floor(root^2/10^h) mod 100 for B+H5, 10^h-B, H5-B (h >= 4) */
    u64 qB = addmod(q100, b100, 100);
    u64 qC = submod(q100, (2 * b100) % 100, 100);
    u64 qD = submod(q100, b100, 100);
    u64 tm11 = tlo % 11, tm100 = tlo % 100;
    u64 rA = b11, rB = addmod(b11, H5M11, 11), rC = submod(PHM11, b11, 11), rD = submod(H5M11, b11, 11);
    if (!(h & 1)) { rA = submod(0, rA, 11); rB = submod(0, rB, 11); rC = submod(0, rC, 11); rD = submod(0, rD, 11); }
    u64 kA = submod(rA, tm11, 11), kB = submod(rB, tm11, 11), kC = submod(rC, tm11, 11), kD = submod(rD, tm11, 11);
    fast_root(B, Q, f, b100, q100, P, W0, W0lo, tlo, T2, kA, tm100, thi, st);
    fast_root(B + H5, Q + B + Q25, f + (1ull << 63), b100, qB, P, W0, W0lo, tlo, T2, kB, tm100, thi, st);
    fast_root(POW10[h] - B, POW10[h] - 2 * B + Q, 0 - f, nb100, qC, P, W0, W0lo, tlo, T2, kC, tm100, thi, st);
    fast_root(H5 - B, Q25 - B + Q, (1ull << 63) - f, nb100, qD, P, W0, W0lo, tlo, T2, kD, tm100, thi, st);
}

static u64 F64[20];  /* floor(2^64 / 10^k) */
static u64 P11[20];  /* 10^k mod 11 */

/* DFS: digits 0..i-1 of B fixed; Qi = floor(Bi^2/10^i); P holds S digits 0..i-1
 * placed at positions h-1..h-i; f ~ Bi*2^64/10^h; b11 = Bi mod 11. */
static void dfs(int i, u64 Bi, u64 Qi, u64 P, u64 f, u64 b11, int unit5, const base_t *bs, stats_t *st)
{
    const int h = G.h;
    base_t local;
    if (i == IB) { make_base(P, &local); bs = &local; }
    int dmax = 9;
    if (i == h - 1) dmax = 4;             /* top digit < 5: partner B + 5*10^(h-1) */
    if (i == 1 && unit5) dmax = 4;        /* unit 5: tens < 5, partner is -B */
    for (u64 d = 0; d <= (u64)dmax; d++) {
        u64 v = Qi + 2 * d * Bi + d * d * POW10[i];
        u64 s = v % 10;
        u64 Pn = P + s * POW10[h - 1 - i];
        u64 Bn = Bi + d * POW10[i];
        u64 fn = f + d * F64[h - i];
        u64 bn = (b11 + d * P11[i]) % 11;
        if (i == h - 1) {
            if (IB == h) { make_base(Pn, &local); bs = &local; }
            if (FAST) fast_leaf(Bn, Pn, v / 10, fn, bn, bs, st);
            else do_leaf(Bn, Pn, v / 10, fn, bn, bs, st);
        } else {
            dfs(i + 1, Bn, v / 10, Pn, fn, bn, unit5, bs, st);
        }
    }
}

/* Task k: unit digit u = 1 + k / 10^(p-1) (1..5), digits 1..p-1 from the rest. */
static int task_valid(u64 k)
{
    u64 per = POW10[G.p - 1];
    u64 u = 1 + k / per, rest = k % per;
    if (u == 5 && G.p >= 2 && (rest % 10) > 4) return 0;
    return 1;
}

static void run_task(u64 k, stats_t *st)
{
    u64 per = POW10[G.p - 1];
    u64 u = 1 + k / per, rest = k % per;
    int unit5 = (u == 5);
    if (unit5 && G.p >= 2 && (rest % 10) > 4) return;
    /* replay the first p digits */
    u64 Bi = 0, Qi = 0, P = 0, f = 0, b11 = 0;
    for (int i = 0; i < G.p; i++) {
        u64 d = (i == 0) ? u : (rest / POW10[i - 1]) % 10;
        u64 v = Qi + 2 * d * Bi + d * d * POW10[i];
        P += (v % 10) * POW10[G.h - 1 - i];
        Bi += d * POW10[i];
        f += d * F64[G.h - i];
        b11 = (b11 + d * P11[i]) % 11;
        Qi = v / 10;
    }
    dfs(G.p, Bi, Qi, P, f, b11, unit5, NULL, st);
}

/* ---------- checkpointing ---------- */

static const char *state_file = NULL;

static void save_state(void)
{
    if (!state_file) return;
    char tmp[1024];
    snprintf(tmp, sizeof tmp, "%s.tmp", state_file);
    FILE *f = fopen(tmp, "wb");
    if (!f) { perror("state"); return; }
    fprintf(f, "A034822 L=%d h=%d p=%d ntasks=%" PRIu64 " lo=%" PRIu64 " hi=%" PRIu64
               " found=%llu nodes=%llu cands=%llu pass=%llu\n",
            G.L, G.h, G.p, G.ntasks, task_lo, task_hi,
            (unsigned long long)atomic_load(&found_count), (unsigned long long)atomic_load(&nodes_total),
            (unsigned long long)atomic_load(&cands_total), (unsigned long long)atomic_load(&pass_total));
    fwrite(done_map, 1, G.ntasks, f);
    fclose(f);
    rename(tmp, state_file);
}

static int load_state(void)
{
    if (!state_file) return 0;
    FILE *f = fopen(state_file, "rb");
    if (!f) return 0;
    int L, h, p;
    u64 nt, lo, hi;
    unsigned long long fc, nd, cd, ps;
    if (fscanf(f, "A034822 L=%d h=%d p=%d ntasks=%" SCNu64 " lo=%" SCNu64 " hi=%" SCNu64
                  " found=%llu nodes=%llu cands=%llu pass=%llu\n",
               &L, &h, &p, &nt, &lo, &hi, &fc, &nd, &cd, &ps) != 10 ||
        L != G.L || h != G.h || p != G.p || nt != G.ntasks) {
        fprintf(stderr, "state file %s does not match parameters\n", state_file);
        exit(1);
    }
    if (fread(done_map, 1, G.ntasks, f) != G.ntasks) { fprintf(stderr, "short state file\n"); exit(1); }
    fclose(f);
    atomic_store(&found_count, fc);
    atomic_store(&nodes_total, nd);
    atomic_store(&cands_total, cd);
    atomic_store(&pass_total, ps);
    return 1;
}

/* ---------- threads ---------- */

static void *worker(void *arg)
{
    (void)arg;
    for (;;) {
        if (stop_flag) break;
        u64 k = atomic_fetch_add(&next_task, 1);
        if (k >= task_hi) break;
        if (done_map[k]) continue;
        stats_t st = {0};
        run_task(k, &st);
        atomic_fetch_add(&nodes_total, st.nodes);
        atomic_fetch_add(&cands_total, st.cands);
        atomic_fetch_add(&pass_total, st.pass);
        atomic_fetch_add(&filt_total, st.filt);
        done_map[k] = 1;
    }
    return NULL;
}

static void on_sigint(int s) { (void)s; stop_flag = 1; }

static double now_sec(void)
{
    struct timespec ts;
    clock_gettime(CLOCK_MONOTONIC, &ts);
    return ts.tv_sec + ts.tv_nsec * 1e-9;
}

static int setup(int L, int h, int p)
{
    G.L = L;
    G.D = (L + 1) / 2;
    int hmin = G.D - 18;
    if ((L - 38 + 1) / 2 > hmin) hmin = (L - 38 + 1) / 2;
    if (hmin < 3) hmin = 3;
    int hmax = (L - 2) / 3;
    if (hmax > 18) hmax = 18;
    if (h <= 0) {
        h = G.D / 2;
        if (h < hmin) h = hmin;
        if (h > hmax) h = hmax;
    }
    if (h < hmin || h > hmax) {
        fprintf(stderr, "L=%d: need %d <= h <= %d (got %d)\n", L, hmin, hmax, h);
        return 0;
    }
    G.h = h;
    G.e = L - 3 * h;
    G.x = (h <= 17) ? 2 : 1;
    if (G.e - G.x < 0 || G.e > 19) { fprintf(stderr, "bad e=%d\n", G.e); return 0; }
    G.pe = POW10[G.e];
    G.pex = POW10[G.e - G.x];
    G.mod11 = (L % 2 == 0);
    if (p <= 0) {
        p = h - 6; /* ~1e6 leaves per task */
        if (p > 7) p = 7;
        if (p < 1) p = 1;
    }
    if (p >= h - 1) p = h - 2;
    if (p < 1) p = 1;
    G.p = p;
    G.ntasks = 5 * POW10[p - 1];
    H5 = 5 * POW10[h - 1];
    Q25 = 25 * POW10[h - 2];
    H5M11 = H5 % 11;
    PHM11 = POW10[h] % 11;
    for (int k = 0; k < 100; k++) REV2[k] = (unsigned char)(10 * (k % 10) + k / 10);
    for (int k = 0; k < 20; k++) {
        F64[k] = k == 0 ? UINT64_MAX : (u64)(((u128)1 << 64) / POW10[k]);
        P11[k] = POW10[k] % 11;
    }
    /* base depth: cubic Taylor remainder Rb*U^3/(16 Pb^3) < 1e-8 with
     * U = 10^(h-IB), Pb >= 10^(h-1), Rb <= 10^((h+e)/2); keep U <= 1e7 */
    {
        /* widest t-window: sqrt(10^e / 10^(h-1)) / 2 + margins */
        double wmax = sqrt(pow(10.0, G.e - h + 1)) / 2.0 + 3.0;
        FAST = G.mod11 && h >= 4 && wmax <= 22.0;
        P4 = (G.x == 2 && G.e >= 4 + 5) ? POW10[G.e - 4] : 0; /* need 10^(e-4) >> SLACK */
    }
    IB = h;
    for (int ib = p; ib <= h; ib++) {
        double lg = (h + G.e) / 2.0 + 3.0 * (1 - ib) - log10(16.0);
        if (lg < -8 && h - ib <= 7) { IB = ib; break; }
    }
    return 1;
}

static u64 run_search(int L, int h, int p, int threads, double interval, u64 ra, u64 rb)
{
    if (!setup(L, h, p)) exit(1);
    task_lo = ra;
    task_hi = rb ? rb : G.ntasks;
    if (task_hi > G.ntasks) task_hi = G.ntasks;
    done_map = calloc(G.ntasks, 1);
    atomic_store(&found_count, 0);
    atomic_store(&nodes_total, 0);
    atomic_store(&cands_total, 0);
    atomic_store(&pass_total, 0);
    atomic_store(&filt_total, 0);
    if (load_state() && !quiet) fprintf(stderr, "resumed from %s\n", state_file);
    for (u64 k = 0; k < G.ntasks; k++)
        if (!task_valid(k)) done_map[k] = 1;
    atomic_store(&next_task, task_lo);
    if (!quiet)
        fprintf(stderr, "L=%d D=%d h=%d e=%d p=%d tasks=[%" PRIu64 ",%" PRIu64 ") of %" PRIu64
                        " mod11=%d threads=%d\n",
                G.L, G.D, G.h, G.e, G.p, task_lo, task_hi, G.ntasks, G.mod11, threads);
    signal(SIGINT, on_sigint);
    signal(SIGTERM, on_sigint);
    pthread_t *th = malloc(sizeof(pthread_t) * threads);
    double t0 = now_sec(), last_save = t0;
    for (int i = 0; i < threads; i++) pthread_create(&th[i], NULL, worker, NULL);
    if (!quiet || interval > 0) {
        for (;;) {
            usleep(200000);
            u64 nt = atomic_load(&next_task);
            int finished = nt >= task_hi + (u64)threads || stop_flag;
            double t = now_sec();
            if (!quiet) {
                u64 done = 0;
                for (u64 k = task_lo; k < task_hi; k++) done += done_map[k];
                double frac = (double)done / (double)(task_hi - task_lo);
                double el = t - t0;
                fprintf(stderr, "\r%6.2f%%  nodes %.3e (%.3g/s)  cands %.3e  found %llu  elapsed %.0fs  eta %.0fs   ",
                        100 * frac, (double)atomic_load(&nodes_total), atomic_load(&nodes_total) / el,
                        (double)atomic_load(&cands_total), (unsigned long long)atomic_load(&found_count), el,
                        frac > 0 ? el / frac - el : 0.0);
            }
            if (state_file && interval > 0 && t - last_save > interval) { save_state(); last_save = t; }
            if (finished) break;
            /* all tasks handed out: wait for threads by checking completion */
            if (nt >= task_hi) {
                int all = 1;
                for (u64 k = task_lo; k < task_hi && all; k++) all = done_map[k];
                if (all) break;
            }
        }
    }
    for (int i = 0; i < threads; i++) pthread_join(th[i], NULL);
    double el = now_sec() - t0;
    save_state();
    int complete = 1;
    for (u64 k = task_lo; k < task_hi; k++) if (!done_map[k]) complete = 0;
    u64 fc = atomic_load(&found_count);
    if (!quiet) fprintf(stderr, "\n");
    printf("%s L=%d count=%" PRIu64 " tasks=[%" PRIu64 ",%" PRIu64 ") nodes=%llu cands=%llu filt=%llu pass=%llu time=%.2fs\n",
           complete ? "DONE" : "PARTIAL", L, fc, task_lo, task_hi, (unsigned long long)atomic_load(&nodes_total),
           (unsigned long long)atomic_load(&cands_total), (unsigned long long)atomic_load(&filt_total),
           (unsigned long long)atomic_load(&pass_total), el);
    fflush(stdout);
    free(th);
    free(done_map);
    return fc;
}

/* ---------- selftest ---------- */

static int cmp_u128(const void *a, const void *b)
{
    u128 x = *(const u128 *)a, y = *(const u128 *)b;
    return x < y ? -1 : x > y;
}

static int selftest(int maxL, int threads)
{
    int bad = 0;
    /* helpers */
    srand(12345);
    for (int i = 0; i < 2000000; i++) {
        u64 d = ((u64)rand() << 33 ^ (u64)rand() << 11 ^ (u64)rand()) % 1000000000000000000ull + 1;
        u64 q = ((u64)rand() << 33 ^ (u64)rand() << 11 ^ (u64)rand());
        u128 x = (u128)q * d + ((u64)rand() * 7919u) % d;
        if (udiv128_64(x, d) != q) { fprintf(stderr, "udiv fail\n"); return 1; }
        u128 y = (u128)q * q + (u64)rand();
        u64 r = isqrt128(y >> 1);
        if (!((u128)r * r <= (y >> 1) && (u128)(r + 1) * (r + 1) > (y >> 1))) { fprintf(stderr, "isqrt fail\n"); return 1; }
    }
    fprintf(stderr, "helpers ok\n");
    quiet = 1;
    for (int L = 11; L <= maxL; L++) {
        /* two different h where possible, to exercise the window logic */
        int D = (L + 1) / 2;
        for (int v = 0; v < 2; v++) {
            int h = D / 2 + v;
            params_t save;
            if (!setup(L, h, 0)) continue;
            save = G;
            (void)save;
            double t0 = now_sec();
            u64 c = run_search(L, h, 0, threads, 0, 0, 0);
            double el = now_sec() - t0;
            int ok = (int)c == KNOWN[L];
            /* all found are distinct genuine palindromic squares */
            u64 m = c < MAXFOUND ? c : MAXFOUND;
            qsort(found_list, m, sizeof(u128), cmp_u128);
            for (u64 i = 1; i < m; i++) if (found_list[i] == found_list[i - 1]) ok = 0;
            fprintf(stderr, "L=%2d h=%2d count=%5" PRIu64 " expected %5d %s  (%.2fs)\n", L, h, c, KNOWN[L],
                    ok ? "ok" : "MISMATCH", el);
            if (!ok) bad++;
        }
    }
    quiet = 0;
    fprintf(stderr, bad ? "SELFTEST FAILED (%d)\n" : "SELFTEST PASSED\n", bad);
    return bad != 0;
}

int main(int argc, char **argv)
{
    POW10[0] = 1;
    for (int i = 1; i < 20; i++) POW10[i] = POW10[i - 1] * 10;
    int threads = (int)sysconf(_SC_NPROCESSORS_ONLN);
    if (argc < 2) goto usage;
    if (!strcmp(argv[1], "check") && argc == 3) {
        u128 n;
        if (!parse_u128(argv[2], &n)) goto usage;
        char ss[128];
        int len = square_digits(n, ss);
        printf("%s^2 = %s (%d digits) %s\n", argv[2], ss, len, is_pal(ss, len) ? "PALINDROME" : "not palindrome");
        return 0;
    }
    if (!strcmp(argv[1], "selftest")) {
        int maxL = argc >= 3 ? atoi(argv[2]) : 40;
        if (argc >= 5 && !strcmp(argv[3], "-t")) threads = atoi(argv[4]);
        return selftest(maxL, threads);
    }
    if (!strcmp(argv[1], "search") && argc >= 3) {
        int L = atoi(argv[2]), h = 0, p = 0;
        double interval = 300;
        u64 ra = 0, rb = 0;
        for (int i = 3; i < argc; i++) {
            if (!strcmp(argv[i], "-t") && i + 1 < argc) threads = atoi(argv[++i]);
            else if (!strcmp(argv[i], "-h") && i + 1 < argc) h = atoi(argv[++i]);
            else if (!strcmp(argv[i], "-p") && i + 1 < argc) p = atoi(argv[++i]);
            else if (!strcmp(argv[i], "-S") && i + 1 < argc) state_file = argv[++i];
            else if (!strcmp(argv[i], "-i") && i + 1 < argc) interval = atof(argv[++i]);
            else if (!strcmp(argv[i], "-r") && i + 1 < argc) {
                if (sscanf(argv[++i], "%" SCNu64 ":%" SCNu64, &ra, &rb) != 2) goto usage;
            } else goto usage;
        }
        if (L < 11 || L > 76) { fprintf(stderr, "L must be in 11..76\n"); return 1; }
        run_search(L, h, p, threads, interval, ra, rb);
        return 0;
    }
usage:
    fprintf(stderr,
            "usage: %s search L [-t threads] [-h H] [-p P] [-S state] [-i secs] [-r a:b]\n"
            "       %s selftest [maxL [-t threads]]\n"
            "       %s check n\n",
            argv[0], argv[0], argv[0]);
    return 2;
}
