#!/usr/bin/env bash
#
# pfgw_split.sh - split an a128344 -F survivor file (PFGW ABC format) into
# N chunks and generate NUMA-pinned launch/status/resume scripts for a
# multi-socket PFGW box.
#
#   ./pfgw_split.sh [-n instances] [-T threads] [-S sockets] \
#                   [-o outdir] [-p pfgw-binary] survivors.abc
#
# Defaults (-n 24 -T 1 -S 2) fit a dual 12-core socket machine: one
# single-threaded instance per physical core, SMT siblings left idle.
# (Measured on dual Xeon 8158: 16x-T1 ran at full solo speed per test -
# gwnum's threaded FFT scales so poorly, and its coordinator thread
# oversubscribes exact-T cpusets so badly, that -T 1 scale-out beats
# every multithreaded config by 2x or more in throughput.)
#
# Survivor lines are dealt round-robin so every chunk gets an even mix of
# small and large k. Each chunk runs in its own directory (chunk_00/ ...)
# so each one's captured output (run.out) stays separate. Then, in outdir:
#
#   ./run_all.sh     launch every unfinished chunk, pinned per socket
#   ./status.sh      per-chunk progress and any PRP hits found
#   ./resume.sh      after a crash: drop already-tested k from each
#                    chunk.abc, then ./run_all.sh to continue
#
# Run run_all.sh under screen/tmux or nohup - it waits for its children.

set -euo pipefail

NINST=24 THREADS=1 SOCKETS=2 OUTDIR=pfgw-run PFGW=pfgw64
usage() {
    echo "usage: $0 [-n instances] [-T threads] [-S sockets]" \
         "[-o outdir] [-p pfgw-binary] survivors.abc" >&2
    exit 2
}
while getopts "n:T:S:o:p:" o; do
    case $o in
    n) NINST=$OPTARG ;;
    T) THREADS=$OPTARG ;;
    S) SOCKETS=$OPTARG ;;
    o) OUTDIR=$OPTARG ;;
    p) PFGW=$OPTARG ;;
    *) usage ;;
    esac
done
shift $((OPTIND - 1))
[ $# -eq 1 ] || usage
ABC=$1
[ -r "$ABC" ] || { echo "$0: cannot read $ABC" >&2; exit 1; }
HEADER=$(head -n1 "$ABC")
case $HEADER in
ABC*) ;;
*) echo "$0: first line of $ABC is not an ABC header" >&2; exit 1 ;;
esac

mkdir -p "$OUTDIR"
i=0
while [ "$i" -lt "$NINST" ]; do
    d=$(printf '%s/chunk_%02d' "$OUTDIR" "$i")
    mkdir -p "$d"
    printf '%s\n' "$HEADER" > "$d/chunk.abc"
    i=$((i + 1))
done

grep '^[0-9]' "$ABC" | awk -v n="$NINST" -v dir="$OUTDIR" '
    { print > sprintf("%s/chunk_%02d/chunk.abc.body", dir, NR % n) }
'
i=0
while [ "$i" -lt "$NINST" ]; do
    d=$(printf '%s/chunk_%02d' "$OUTDIR" "$i")
    [ -f "$d/chunk.abc.body" ] && cat "$d/chunk.abc.body" >> "$d/chunk.abc"
    rm -f "$d/chunk.abc.body"
    i=$((i + 1))
done

{
    echo "# chunk  socket  threads  count  kmin  kmax"
    i=0
    while [ "$i" -lt "$NINST" ]; do
        d=$(printf 'chunk_%02d' "$i")
        s=$((i % SOCKETS))
        grep '^[0-9]' "$OUTDIR/$d/chunk.abc" | sort -n | awk \
            -v d="$d" -v s="$s" -v t="$THREADS" '
            NR==1 { min=$1 }
            { max=$1 }
            END { printf "%s  %d  %d  %d  %s  %s\n",
                  d, s, t, NR, NR?min:"-", NR?max:"-" }'
        i=$((i + 1))
    done
} > "$OUTDIR/manifest.txt"

cat > "$OUTDIR/run_all.sh" <<EOF
#!/usr/bin/env bash
# generated by pfgw_split.sh - launch all unfinished chunks, each pinned
# to its own disjoint set of physical cores (gwnum instances otherwise
# tend to stack their threads on the same first cores)
set -u
cd "\$(dirname "\$0")"
PFGW="$PFGW"
THREADS=$THREADS
SOCKETS=$SOCKETS
EOF
cat >> "$OUTDIR/run_all.sh" <<'EOF'
# per-socket lists of one logical CPU per physical core (no SMT siblings)
NODECPUS=()
HAVE_TOPO=0
if command -v lscpu >/dev/null 2>&1 && \
   command -v numactl >/dev/null 2>&1; then
    while read -r sock cpus; do
        NODECPUS[$sock]="$cpus"
        HAVE_TOPO=1
    done < <(lscpu -p=CPU,CORE,SOCKET | awk -F, '
        /^[0-9]/ {
            key = $3 ":" $2
            if (!(key in seen)) { seen[key] = 1; list[$3] = list[$3] " " $1 }
        }
        END { for (s in list) print s, list[s] }')
elif ! command -v numactl >/dev/null 2>&1; then
    echo "warning: numactl not found; running without pinning" >&2
fi

i=0
warned=0
for d in chunk_*/; do
    d=${d%/}
    s=$((i % SOCKETS))
    idx=$((i / SOCKETS))
    i=$((i + 1))
    if ! grep -q '^[0-9]' "$d/chunk.abc"; then
        echo "$d: nothing to do"
        continue
    fi
    PIN=""
    where="unpinned"
    if [ "$HAVE_TOPO" = 1 ]; then
        arr=(${NODECPUS[$s]:-})
        start=$((idx * THREADS))
        if [ $((start + THREADS)) -le ${#arr[@]} ]; then
            slice=("${arr[@]:$start:$THREADS}")
            cpulist=$(IFS=,; echo "${slice[*]}")
            PIN="numactl --physcpubind=$cpulist --membind=$s"
            where="socket $s cpus $cpulist"
        else
            if [ "$warned" = 0 ]; then
                echo "warning: more instances*threads than physical" \
                     "cores; falling back to node binding" >&2
                warned=1
            fi
            PIN="numactl --cpunodebind=$s --membind=$s"
            where="socket $s (node bind)"
        fi
    elif command -v numactl >/dev/null 2>&1; then
        PIN="numactl --cpunodebind=$s --membind=$s"
        where="socket $s (node bind)"
    fi
    ( cd "$d" && exec $PIN "$PFGW" -f0 -T"$THREADS" chunk.abc \
        >> run.out 2>&1 ) &
    echo "launched $d on $where (pid $!)"
done
echo "waiting for all chunks (use ./status.sh from another shell)"
wait
echo "all chunks finished"
EOF
chmod +x "$OUTDIR/run_all.sh"

cat > "$OUTDIR/status.sh" <<'EOF'
#!/usr/bin/env bash
# generated by pfgw_split.sh - per-chunk progress and PRP hits.
# Results are parsed from PFGW's captured stdout (run.out), which mixes
# \r-separated progress updates with result lines; pfgw.log is also read
# if PFGW was configured to write one.
set -u
cd "$(dirname "$0")"
results() {   # $1 = chunk dir -> "k<TAB>result line", one per tested k
    cat "$1"/run.out "$1"/pfgw.log 2>/dev/null | tr '\r' '\n' \
        | sed -nE 's|^\(7\^([0-9]+)-5\^[0-9]+\)/2 is (.*)|\1	\1 is \2|p' \
        | sort -t '	' -k1,1n -u
}
printf '%-10s %8s %8s %8s\n' chunk total done left
tot=0; don=0
for d in chunk_*/; do
    d=${d%/}
    src="$d/chunk.abc"; [ -f "$d/chunk.abc.orig" ] && src="$d/chunk.abc.orig"
    total=$(grep -c '^[0-9]' "$src" 2>/dev/null || true)
    done_n=$(results "$d" | wc -l | tr -d ' ')
    printf '%-10s %8d %8d %8d\n' "$d" "$total" "$done_n" \
        $((total > done_n ? total - done_n : 0))
    tot=$((tot + total)); don=$((don + done_n))
done
printf '%-10s %8d %8d %8d\n' TOTAL "$tot" "$don" $((tot > don ? tot - don : 0))
hits=$(for d in chunk_*/; do results "${d%/}"; done \
       | cut -f2 | grep -Ei 'PRP|is prime' || true)
if [ -n "$hits" ]; then
    echo
    echo "*** HITS ***   (k = (7^k-5^k)/2)"
    printf '%s\n' "$hits"
fi
EOF
chmod +x "$OUTDIR/status.sh"

cat > "$OUTDIR/resume.sh" <<'EOF'
#!/usr/bin/env bash
# generated by pfgw_split.sh - after a crash, drop already-tested k from
# each chunk.abc (parsed from run.out / pfgw.log), then ./run_all.sh to
# continue
set -eu
cd "$(dirname "$0")"
for d in chunk_*/; do
    d=${d%/}
    cat "$d"/run.out "$d"/pfgw.log 2>/dev/null | tr '\r' '\n' \
        | sed -nE 's|^\(7\^([0-9]+)-5\^[0-9]+\)/2 is .*|\1|p' \
        | sort -u > "$d/.done"
    [ -f "$d/chunk.abc.orig" ] || cp "$d/chunk.abc" "$d/chunk.abc.orig"
    before=$(grep -c '^[0-9]' "$d/chunk.abc" || true)
    if [ -s "$d/.done" ]; then
        awk 'NR==FNR { done[$1]=1; next }
             FNR==1 || (/^[0-9]/ && !($1 in done))' \
            "$d/.done" "$d/chunk.abc" > "$d/chunk.abc.new"
        mv "$d/chunk.abc.new" "$d/chunk.abc"
    fi
    after=$(grep -c '^[0-9]' "$d/chunk.abc" || true)
    echo "$d: $before -> $after remaining"
done
echo "chunks pruned; ./run_all.sh to continue"
EOF
chmod +x "$OUTDIR/resume.sh"

echo "wrote $OUTDIR/: $(ls "$OUTDIR")"
sed 's/^/  /' "$OUTDIR/manifest.txt"
