// gpu_metal.mm - Apple Metal engine.  The table lives in unified memory: the CPU builds it
// straight into shared MTLBuffers, the GPU enumerates the outer digits and probes it.
#import <Foundation/Foundation.h>
#import <Metal/Metal.h>

#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <functional>
#include <map>
#include <stdexcept>
#include <string>
#include <thread>

#include "gpu.h"

// core.h + kernels.metal, generated by the Makefile (runtime compilation: no offline Metal toolchain needed)
static const char* kKernelSource =
#include "kernels_src.inc"
    ;

struct KArgs {
  uint32_t nSuffix, nPrefix, hitCap, candCap;
};

struct Pipelines {
  id<MTLComputePipelineState> search, prep, check;
  id<MTLComputePipelineState> v2zero, v2bgen, scanLocal, scanBlocks, scanAdd, v2agen, v2indirect, v2check;
};

struct GpuEngine {
  id<MTLDevice> dev;
  id<MTLCommandQueue> queue;
  std::string name;
  bool verbose = false;
  std::map<std::string, Pipelines> cache;  // specialised kernels by #define prelude
  id<MTLBuffer> offsBuf, entsBuf;          // reused across lengths
};

static id<MTLLibrary> compile_lib(id<MTLDevice> dev, const std::string& prelude) {
  NSError* err = nil;
  MTLCompileOptions* opts = [MTLCompileOptions new];
  opts.languageVersion = MTLLanguageVersion3_1;
  std::string src = "#define NLIMB " + std::to_string(NLIMB) + "\n" + prelude + kKernelSource;
  id<MTLLibrary> lib = [dev newLibraryWithSource:[NSString stringWithUTF8String:src.c_str()] options:opts error:&err];
  if (!lib) throw std::runtime_error(std::string("Metal compile failed: ") + (err ? err.localizedDescription.UTF8String : "?"));
  return lib;
}

static id<MTLComputePipelineState> make_pso(id<MTLDevice> dev, id<MTLLibrary> lib, const char* name) {
  NSError* err = nil;
  id<MTLFunction> fn = [lib newFunctionWithName:[NSString stringWithUTF8String:name]];
  if (!fn) throw std::runtime_error(std::string("missing kernel ") + name);
  id<MTLComputePipelineState> pso = [dev newComputePipelineStateWithFunction:fn error:&err];
  if (!pso) throw std::runtime_error(std::string("pipeline failed: ") + (err ? err.localizedDescription.UTF8String : "?"));
  return pso;
}

// Constants of this search baked into the kernel source.
static std::string spec_prelude(const Params& p) {
  char buf[768];
  snprintf(buf, sizeof buf,
           "#define SPEC_Q %u\n#define SPEC_P %u\n#define SPEC_C %u\n#define SPEC_RHO %lluull\n#define SPEC_QBITS %u\n"
           "#define SPEC_GMODE %u\n#define SPEC_T %u\n#define SPEC_UEFF %u\n#define SPEC_NSEG %u\n#define SPEC_REVR %u\n"
           "#define SPEC_R %u\n#define SPEC_TP %u\n#define SPEC_V2U %u\n#define SPEC_R0 %u\n",
           p.Q, p.P, p.c, (unsigned long long)p.rho, p.qbits, p.gmode, p.t, p.ueff, p.nseg, p.revR, p.r, p.tp, p.v2u,
           p.r0);
  return buf;
}

static Pipelines& pipelines_for(GpuEngine* g, const Params& p) {
  std::string pre = spec_prelude(p);
  auto it = g->cache.find(pre);
  if (it != g->cache.end()) return it->second;
  auto t0 = std::chrono::steady_clock::now();
  id<MTLLibrary> lib = compile_lib(g->dev, pre);
  Pipelines pl{make_pso(g->dev, lib, "search_nodes"), make_pso(g->dev, lib, "prep_indirect"),
               make_pso(g->dev, lib, "check_cands"),  make_pso(g->dev, lib, "v2_zero"),
               make_pso(g->dev, lib, "v2_bgen"),      make_pso(g->dev, lib, "scan_local"),
               make_pso(g->dev, lib, "scan_blocks"),  make_pso(g->dev, lib, "scan_add"),
               make_pso(g->dev, lib, "v2_agen"),      make_pso(g->dev, lib, "v2_indirect"),
               make_pso(g->dev, lib, "v2_check")};
  if (g->verbose)
    fprintf(stderr, "    compiled specialised kernels in %.2fs\n",
            std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count());
  return g->cache[pre] = pl;
}

static id<MTLBuffer> shared_buffer(id<MTLDevice> dev, size_t bytes) {
  if (bytes == 0) bytes = 16;
  id<MTLBuffer> b = [dev newBufferWithLength:bytes options:MTLResourceStorageModeShared];
  if (!b) throw std::runtime_error("Metal buffer allocation failed (" + std::to_string(bytes) + " bytes)");
  return b;
}

static id<MTLBuffer> buffer_with(id<MTLDevice> dev, const void* data, size_t bytes) {
  id<MTLBuffer> b = shared_buffer(dev, bytes);
  if (bytes) memcpy(b.contents, data, bytes);
  return b;
}

GpuEngine* gpu_create(bool verbose) {
  @autoreleasepool {
    id<MTLDevice> dev = MTLCreateSystemDefaultDevice();
    if (!dev) return nullptr;
    try {
      auto t0 = std::chrono::steady_clock::now();
      id<MTLLibrary> lib = compile_lib(dev, "");
      // layout check: host and device must agree on the Params struct
      id<MTLComputePipelineState> lp = make_pso(dev, lib, "layout_check");
      Params p{};
      p.Q = 7;
      p.seg[1].LQ = 1234;
      p.qpow[3] = 0xabcdef12345ull;
      p.centerDig[1] = 77;
      p.Wmax.l[1] = 0x55aa55aa11ull;
      p.recLoN = 4242;
      id<MTLBuffer> pb = buffer_with(dev, &p, sizeof(Params));
      id<MTLBuffer> ob = shared_buffer(dev, 64);
      id<MTLCommandQueue> q = [dev newCommandQueue];
      id<MTLCommandBuffer> cb = [q commandBuffer];
      id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
      [enc setComputePipelineState:lp];
      [enc setBuffer:ob offset:0 atIndex:0];
      [enc setBuffer:pb offset:0 atIndex:1];
      [enc dispatchThreads:MTLSizeMake(1, 1, 1) threadsPerThreadgroup:MTLSizeMake(1, 1, 1)];
      [enc endEncoding];
      [cb commit];
      [cb waitUntilCompleted];
      const uint32_t* o = (const uint32_t*)ob.contents;
      bool ok = o[0] == sizeof(Params) && o[1] == sizeof(SegInfo) && o[2] == sizeof(NumQ) &&
                o[3] == sizeof(FastDiv) && o[4] == 7 && o[5] == 1234 &&
                o[6] == (uint32_t)(p.qpow[3] & 0xffffffffu) && o[7] == 77 &&
                o[8] == (uint32_t)(p.Wmax.l[1] & 0xffffffffu) && o[9] == 4242;
      if (!ok) {
        fprintf(stderr, "Metal layout mismatch: sizeof(Params) host %zu device %u\n", sizeof(Params), o[0]);
        return nullptr;
      }
      auto* g = new GpuEngine();
      g->dev = dev;
      g->queue = [dev newCommandQueue];
      g->verbose = verbose;
      g->name = std::string("gpu: ") + dev.name.UTF8String;
      if (verbose)
        fprintf(stderr, "# Metal kernels compiled in %.2fs; layout check OK\n",
                std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count());
      return g;
    } catch (std::exception& e) {
      fprintf(stderr, "%s\n", e.what());
      return nullptr;
    }
  }
}

const char* gpu_name(GpuEngine* g) { return g ? g->name.c_str() : "none"; }

void gpu_destroy(GpuEngine* g) { delete g; }

namespace {
struct Slot {
  id<MTLBuffer> prefix, counters, hits, cands, indirect;
  id<MTLCommandBuffer> cb;
  uint32_t nPrefix = 0;
  uint64_t nodes = 0;
  uint32_t p0 = 0, p1 = 0;  // prefix range of the command buffer in flight
};
}  // namespace

RunStats run_gpu(GpuEngine* g, const Plan& pl, int threads, std::vector<NumQ>& found, double* tableSeconds,
                 bool verbose) {
  @autoreleasepool {
    const Params& p = pl.prm;
    RunStats st;
    // ---- table (CPU-built, in shared memory) --------------------------------------------------
    size_t ob = table_offs_bytes(pl), eb = table_ents_bytes(pl);
    if (!g->offsBuf || g->offsBuf.length < ob) {
      g->offsBuf = nil;
      g->offsBuf = shared_buffer(g->dev, ob);
    }
    if (!g->entsBuf || g->entsBuf.length < eb) {
      g->entsBuf = nil;
      g->entsBuf = shared_buffer(g->dev, eb);
    }
    TableView tv{(u32*)g->offsBuf.contents, (u64*)g->entsBuf.contents};
    double tb = build_table(pl, tv, threads);
    if (tableSeconds) *tableSeconds = tb;

    auto t0 = std::chrono::steady_clock::now();
    // ---- split the outer digits: prefixes (CPU, with pruning) x suffixes (GPU grid) ------------
    u32 ks = 0;
    u64 nSuffix = 1;
    const u64 suffixMax = p.gmode ? 1000 : 600000;
    while (ks + 1 < p.k && nSuffix * p.P <= suffixMax) {
      nSuffix *= p.P;
      ks++;
    }
    u32 k0 = p.k - ks;
    std::vector<NumQ> suffix(nSuffix);
    for (u64 x = 0; x < nSuffix; x++) {
      NumQ acc{};
      u64 r = x;
      for (int i = (int)p.k - 1; i >= (int)k0; i--) {
        u32 d = (u32)(r % p.P);
        r /= p.P;
        if (d) acc = nq_add(acc, pl.outerW[(size_t)i * p.P + d], p.rho);
      }
      suffix[x] = acc;
    }
    id<MTLBuffer> paramsBuf = buffer_with(g->dev, &p, sizeof(Params));
    id<MTLBuffer> suffixBuf = buffer_with(g->dev, suffix.data(), suffix.size() * sizeof(NumQ));
    id<MTLBuffer> revBuf = buffer_with(g->dev, pl.revtab.data(), pl.revtab.size() * sizeof(u32));
    id<MTLBuffer> hiBuf = buffer_with(g->dev, pl.recHi.data(), pl.recHi.size() * sizeof(NumQ));
    id<MTLBuffer> loBuf = buffer_with(g->dev, pl.recLo.data(), pl.recLo.size() * sizeof(NumQ));

    Pipelines& pso = pipelines_for(g, p);
    const uint32_t hitCap = 4096;
    // ~2^27 nodes per dispatch, fewer when candidates are frequent (deferred buffer of 2^24 records)
    const uint32_t candCap = 1u << 24;
    double candRate = pl.nodesEst > 0 ? pl.candsEst / pl.nodesEst : 0.0;
    double nodesPerDispatch = std::min(double(1ull << 27), 0.5 * candCap / std::max(candRate, 1e-9));
    uint32_t perBatch = (uint32_t)std::max<double>(1.0, std::floor(nodesPerDispatch / (double)nSuffix));
    const int NS = 3;
    Slot slots[NS];
    for (auto& s : slots) {
      s.prefix = shared_buffer(g->dev, (size_t)perBatch * sizeof(NumQ));
      s.counters = shared_buffer(g->dev, 16 * sizeof(uint32_t));
      s.hits = shared_buffer(g->dev, (size_t)hitCap * sizeof(NumQ));
      s.cands = [g->dev newBufferWithLength:(size_t)candCap * 12 options:MTLResourceStorageModePrivate];
      s.indirect = shared_buffer(g->dev, 16);
      s.cb = nil;
    }
    NSUInteger tg = std::min<NSUInteger>(256, pso.search.maxTotalThreadsPerThreadgroup);
    u64 deferred = 0;

    auto harvest = [&](Slot& s) -> bool {
      if (!s.cb) return true;
      [s.cb waitUntilCompleted];
      bool ok = s.cb.status != MTLCommandBufferStatusError;
      if (ok) {
        const uint32_t* c = (const uint32_t*)s.counters.contents;
        uint32_t nh = c[0];
        if (nh > hitCap) throw std::runtime_error("GPU hit buffer overflow");
        const NumQ* h = (const NumQ*)s.hits.contents;
        found.insert(found.end(), h, h + nh);
        st.probes += c[1];
        st.cands += c[2];
        st.overflow += c[3];
        deferred += std::min(c[4], candCap);
        st.nodes += s.nodes;
      } else if (verbose) {
        NSError* e = s.cb.error;
        fprintf(stderr, "    command buffer failed (%s); re-running in smaller pieces\n",
                e ? e.localizedDescription.UTF8String : "?");
      }
      s.cb = nil;
      return ok;
    };
    auto submit_part = [&](Slot& s, uint32_t p0, uint32_t p1) {
      memset(s.counters.contents, 0, 16 * sizeof(uint32_t));
      KArgs ka{(uint32_t)nSuffix, p1 - p0, hitCap, candCap};
      id<MTLCommandBuffer> cb = [g->queue commandBuffer];
      id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
      [enc setComputePipelineState:pso.search];
      [enc setBuffer:paramsBuf offset:0 atIndex:0];
      [enc setBuffer:s.prefix offset:(NSUInteger)p0 * sizeof(NumQ) atIndex:1];
      [enc setBuffer:suffixBuf offset:0 atIndex:2];
      [enc setBuffer:revBuf offset:0 atIndex:3];
      [enc setBuffer:g->offsBuf offset:0 atIndex:4];
      [enc setBuffer:g->entsBuf offset:0 atIndex:5];
      [enc setBuffer:hiBuf offset:0 atIndex:6];
      [enc setBuffer:loBuf offset:0 atIndex:7];
      [enc setBuffer:s.counters offset:0 atIndex:8];
      [enc setBuffer:s.hits offset:0 atIndex:9];
      [enc setBytes:&ka length:sizeof(ka) atIndex:10];
      [enc setBuffer:s.cands offset:0 atIndex:11];
      [enc dispatchThreads:MTLSizeMake(nSuffix, p1 - p0, 1) threadsPerThreadgroup:MTLSizeMake(tg, 1, 1)];
      // second pass: full tests of the deferred candidates
      [enc setComputePipelineState:pso.prep];
      [enc setBuffer:s.counters offset:0 atIndex:0];
      [enc setBuffer:s.indirect offset:0 atIndex:1];
      [enc setBytes:&ka length:sizeof(ka) atIndex:2];
      [enc dispatchThreads:MTLSizeMake(1, 1, 1) threadsPerThreadgroup:MTLSizeMake(1, 1, 1)];
      [enc setComputePipelineState:pso.check];
      [enc setBuffer:paramsBuf offset:0 atIndex:0];
      [enc setBuffer:s.prefix offset:(NSUInteger)p0 * sizeof(NumQ) atIndex:1];
      [enc setBuffer:suffixBuf offset:0 atIndex:2];
      [enc setBuffer:revBuf offset:0 atIndex:3];
      [enc setBuffer:hiBuf offset:0 atIndex:6];
      [enc setBuffer:loBuf offset:0 atIndex:7];
      [enc setBuffer:s.counters offset:0 atIndex:8];
      [enc setBuffer:s.hits offset:0 atIndex:9];
      [enc setBytes:&ka length:sizeof(ka) atIndex:10];
      [enc setBuffer:s.cands offset:0 atIndex:11];
      [enc dispatchThreadgroupsWithIndirectBuffer:s.indirect
                             indirectBufferOffset:0
                            threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
      [enc endEncoding];
      [cb commit];
      s.cb = cb;
      s.nodes = nSuffix * (u64)(p1 - p0);
      s.p0 = p0;
      s.p1 = p1;
    };

    auto submit = [&](Slot& s) { submit_part(s, 0, s.nPrefix); };
    std::function<void(Slot&, uint32_t, uint32_t, int)> redo = [&](Slot& s, uint32_t p0, uint32_t p1, int tries) {
      submit_part(s, p0, p1);
      if (harvest(s)) return;
      if (p1 - p0 > 1) {
        uint32_t mid = p0 + (p1 - p0) / 2;
        redo(s, p0, mid, 3);
        redo(s, mid, p1, 3);
      } else if (tries > 1) {
        redo(s, p0, p1, tries - 1);
      } else {
        throw std::runtime_error("GPU command buffer keeps failing on a single prefix");
      }
    };
    auto settle = [&](Slot& s) {
      uint32_t p0 = s.p0, p1 = s.p1;
      if (!harvest(s)) redo(s, p0, p1, 3);
    };
    int cur = 0;
    double totalPrefix = (double)pl.topDigits.size() * std::pow((double)p.P, (double)k0 - 1);
    u64 emitted = 0;
    auto lastReport = std::chrono::steady_clock::now();
    settle(slots[cur]);
    slots[cur].nPrefix = 0;
    u64 seenPrefix = 0;
    st.pruned += gen_prefixes(pl, k0, [&](const NumQ& C) {
      if (seenPrefix++ % pl.partN != pl.partI) return;  // --part i/n: interleaved prefixes
      Slot& s = slots[cur];
      ((NumQ*)s.prefix.contents)[s.nPrefix++] = C;
      emitted++;
      if (s.nPrefix == perBatch) {
        submit(s);
        cur = (cur + 1) % NS;
        settle(slots[cur]);
        slots[cur].nPrefix = 0;
        auto now = std::chrono::steady_clock::now();
        if (verbose || std::chrono::duration<double>(now - lastReport).count() > 30) {
          double el = std::chrono::duration<double>(now - t0).count();
          double frac = emitted * (double)pl.partN / totalPrefix;
          fprintf(stderr, "    L=%u  %.2f%% of prefixes  %.3g nodes/s  elapsed %.0fs  eta %.0fs\n", pl.L,
                  100.0 * frac, (double)st.nodes / std::max(el, 1e-9), el, el / std::max(frac, 1e-12) - el);
          lastReport = now;
        }
      }
    });
    if (slots[cur].nPrefix) submit(slots[cur]);
    for (auto& s : slots) settle(s);
    st.seconds = std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
    if (verbose)
      fprintf(stderr, "    gpu: k0=%u ks=%u suffix=%llu perBatch=%u deferred=%.3g  %.3g nodes/s\n", k0, ks,
              (unsigned long long)nSuffix, perBatch, (double)deferred, st.nodes / std::max(st.seconds, 1e-9));
    return st;
  }
}

// =============================================================================================
// v2 on the GPU
// =============================================================================================
struct V2Args {
  uint64_t c0;
  uint32_t ww, nBuckets, nB1, subB, nPieces, subA, hitCap, candCap, nBlocks, pad;
};

template <class T>
static id<MTLBuffer> vec_buffer(id<MTLDevice> dev, const std::vector<T>& v) {
  return buffer_with(dev, v.data(), v.size() * sizeof(T));
}

RunStats run_gpu2(GpuEngine* g, const Plan2& p2, int threads, std::vector<NumQ>& found, bool verbose) {
  @autoreleasepool {
    const Params& p = p2.base.prm;
    RunStats st;
    auto t0 = std::chrono::steady_clock::now();
    Pipelines& pso = pipelines_for(g, p);
    const u64 Qr = p.Qr, w = p.w, nb = (Qr + w - 1) / w;
    std::vector<u64> mine;  // --part i/n: interleaved batches
    for (u64 bi = p2.base.partI; bi < nb; bi += p2.base.partN) mine.push_back(bi);
    const u64 nm = mine.size();
    const uint32_t nBuckets = (uint32_t)(w * p.qpow[p.tp]);
    const uint32_t nBlocks = (nBuckets + 2 + 1023) / 1024;
    // exact size of every batch table (so the entry buffer can never overflow)
    std::vector<u64> bcount(nm, 0);
    {
      std::vector<std::thread> th;
      int T = std::max(1, threads);
      for (int t = 0; t < T; t++)
        th.emplace_back([&, t] {
          for (u64 j = t; j < nm; j += T) {
            u64 bi = mine[j];
            u64 c0 = bi * w, ww = std::min(w, Qr - c0), tot = 0;
            for (u32 b1 = 0; b1 < p.nB1; b1++) {
              u64 lo = (c0 + Qr - (p2.b1V[b1] / p.qpow[p.r0]) % Qr) % Qr;
              if (lo + ww <= Qr)
                tot += p2.b2Offs[lo + ww] - p2.b2Offs[lo];
              else
                tot += (p2.b2Offs[Qr] - p2.b2Offs[lo]) + (p2.b2Offs[lo + ww - Qr] - p2.b2Offs[0]);
            }
            bcount[j] = tot;
          }
        });
      for (auto& x : th) x.join();
    }
    u64 maxEnts = 1;
    for (u64 c : bcount) maxEnts = std::max(maxEnts, c);
    // static data
    id<MTLBuffer> paramsBuf = buffer_with(g->dev, &p, sizeof(Params));
    id<MTLBuffer> revBuf = vec_buffer(g->dev, p2.base.revtab);
    id<MTLBuffer> ahiBuf = vec_buffer(g->dev, p2.ahi);
    std::vector<u64> ahiRb(p2.ahi.size());  // class bases only: cheap per-batch screening of pieces
    for (size_t i = 0; i < p2.ahi.size(); i++) ahiRb[i] = p2.ahi[i].Rr;
    id<MTLBuffer> ahiRbBuf = vec_buffer(g->dev, ahiRb);
    id<MTLBuffer> aloCBuf = vec_buffer(g->dev, p2.aloC);
    id<MTLBuffer> aloOffsBuf = vec_buffer(g->dev, p2.aloOffs);
    id<MTLBuffer> b1VBuf = vec_buffer(g->dev, p2.b1V);
    id<MTLBuffer> recB1Buf = vec_buffer(g->dev, p2.recB1);
    id<MTLBuffer> b2VBuf = vec_buffer(g->dev, p2.b2V);
    id<MTLBuffer> b2IdxBuf = vec_buffer(g->dev, p2.b2Idx);
    id<MTLBuffer> b2OffsBuf = vec_buffer(g->dev, p2.b2Offs);
    id<MTLBuffer> midWBuf = vec_buffer(g->dev, p2.base.midW);
    id<MTLBuffer> cenWBuf = vec_buffer(g->dev, p2.base.cenW);
    const uint32_t hitCap = 4096, candCap = 1u << 24;
    const uint32_t nPieces = (uint32_t)p2.ahi.size();
    const uint32_t subB = (uint32_t)std::max<u64>(1, (65536 + p.nB1 - 1) / p.nB1);
    const uint32_t subA = (uint32_t)std::max<u64>(1, (65536 + nPieces - 1) / nPieces);
    // batches per command buffer: ~2^28 nodes
    double nodesPerBatch = (double)p2.nA / (double)nb;
    u64 G = (u64)std::max(1.0, std::min(256.0, std::floor((double)(1u << 25) / std::max(nodesPerBatch, 1.0))));
    struct Slot2 {
      id<MTLBuffer> A, blk, ents, cbuf, counters, hits, ind;
      id<MTLCommandBuffer> cb;
      u64 j0 = 0, j1 = 0;  // batches (indices into `mine`) of the command buffer in flight
    };
    const int NS = 2;
    Slot2 slots[NS];
    for (auto& s : slots) {
      s.A = shared_buffer(g->dev, ((size_t)nBuckets + 2) * 4);
      s.blk = shared_buffer(g->dev, (size_t)nBlocks * 4 + 16);
      s.ents = [g->dev newBufferWithLength:(size_t)maxEnts * 8 options:MTLResourceStorageModePrivate];
      s.cbuf = [g->dev newBufferWithLength:(size_t)candCap * 16 options:MTLResourceStorageModePrivate];
      s.counters = shared_buffer(g->dev, 16 * 4);
      s.hits = shared_buffer(g->dev, (size_t)hitCap * sizeof(NumQ));
      s.ind = shared_buffer(g->dev, 16);
      s.cb = nil;
    }
    u64 prefPass = 0;
    // A command buffer that runs too long on a machine driving a display is killed by macOS
    // ("Impacting Interactivity").  Command buffers are therefore sized from measured GPU time,
    // and a failed one is re-run synchronously in smaller pieces (results of a failed buffer are
    // discarded, so nothing is counted twice).
    double lastTimePerBatch = 0;
    auto harvest = [&](Slot2& s) -> bool {
      if (!s.cb) return true;
      [s.cb waitUntilCompleted];
      bool ok = s.cb.status != MTLCommandBufferStatusError;
      if (ok) {
        const uint32_t* c = (const uint32_t*)s.counters.contents;
        if (c[0] > hitCap) throw std::runtime_error("GPU hit buffer overflow");
        const NumQ* h = (const NumQ*)s.hits.contents;
        found.insert(found.end(), h, h + c[0]);
        st.probes += c[1];
        st.cands += c[2];
        st.overflow += c[3];
        st.nodes += c[5];
        prefPass += c[6];
        double dt = s.cb.GPUEndTime - s.cb.GPUStartTime;
        if (dt > 0 && s.j1 > s.j0) lastTimePerBatch = dt / (double)(s.j1 - s.j0);
      } else if (verbose) {
        NSError* e = s.cb.error;
        fprintf(stderr, "    command buffer failed (%s); re-running %llu batches in smaller pieces\n",
                e ? e.localizedDescription.UTF8String : "?", (unsigned long long)(s.j1 - s.j0));
      }
      s.cb = nil;
      return ok;
    };
    auto grid1 = [](id<MTLComputeCommandEncoder> enc, NSUInteger n) {
      [enc dispatchThreads:MTLSizeMake(std::max<NSUInteger>(n, 1), 1, 1) threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
    };
    auto encode_batch = [&](id<MTLComputeCommandEncoder> enc, Slot2& s, u64 bi) {
      V2Args va{};
      va.c0 = bi * w;
      va.ww = (uint32_t)std::min(w, Qr - va.c0);
      va.nBuckets = nBuckets;
      va.nB1 = p.nB1;
      va.subB = subB;
      va.nPieces = nPieces;
      va.subA = subA;
      va.hitCap = hitCap;
      va.candCap = candCap;
      va.nBlocks = nBlocks;
      uint32_t zero = 0, one = 1;
      // 1. clear the bucket counters and the deferred-candidate count
      [enc setComputePipelineState:pso.v2zero];
      [enc setBuffer:s.A offset:0 atIndex:0];
      [enc setBytes:&va length:sizeof va atIndex:1];
      [enc setBuffer:s.counters offset:0 atIndex:2];
      grid1(enc, nBuckets + 2);
      // 2. count middles per bucket; 4. (below) scatter them -- same kernel, flag at index 8
      auto bgen = [&](uint32_t* flag) {
        [enc setComputePipelineState:pso.v2bgen];
        [enc setBuffer:paramsBuf offset:0 atIndex:0];
        [enc setBytes:&va length:sizeof va atIndex:1];
        [enc setBuffer:b1VBuf offset:0 atIndex:2];
        [enc setBuffer:b2VBuf offset:0 atIndex:3];
        [enc setBuffer:b2IdxBuf offset:0 atIndex:4];
        [enc setBuffer:b2OffsBuf offset:0 atIndex:5];
        [enc setBuffer:s.A offset:0 atIndex:6];
        [enc setBuffer:s.ents offset:0 atIndex:7];
        [enc setBytes:flag length:4 atIndex:8];
        [enc dispatchThreads:MTLSizeMake(p.nB1, subB, 1)
            threadsPerThreadgroup:MTLSizeMake(std::min<u32>(256, p.nB1), 1, 1)];
      };
      bgen(&zero);
      // 3. inclusive scan
      [enc setComputePipelineState:pso.scanLocal];
      [enc setBuffer:s.A offset:0 atIndex:0];
      [enc setBuffer:s.blk offset:0 atIndex:1];
      [enc setBytes:&va length:sizeof va atIndex:2];
      [enc dispatchThreadgroups:MTLSizeMake(nBlocks, 1, 1) threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
      [enc setComputePipelineState:pso.scanBlocks];
      [enc setBuffer:s.blk offset:0 atIndex:1];
      [enc setBytes:&va length:sizeof va atIndex:2];
      [enc dispatchThreadgroups:MTLSizeMake(1, 1, 1) threadsPerThreadgroup:MTLSizeMake(1024, 1, 1)];
      [enc setComputePipelineState:pso.scanAdd];
      [enc setBuffer:s.A offset:0 atIndex:0];
      [enc setBuffer:s.blk offset:0 atIndex:1];
      [enc setBytes:&va length:sizeof va atIndex:2];
      grid1(enc, nBuckets + 2);
      // 4. scatter middles
      bgen(&one);
      // 5. outer parts of the same classes: probe
      [enc setComputePipelineState:pso.v2agen];
      [enc setBuffer:paramsBuf offset:0 atIndex:0];
      [enc setBytes:&va length:sizeof va atIndex:1];
      [enc setBuffer:ahiBuf offset:0 atIndex:2];
      [enc setBuffer:aloCBuf offset:0 atIndex:3];
      [enc setBuffer:aloOffsBuf offset:0 atIndex:4];
      [enc setBuffer:s.A offset:0 atIndex:5];
      [enc setBuffer:s.ents offset:0 atIndex:6];
      [enc setBuffer:revBuf offset:0 atIndex:7];
      [enc setBuffer:s.counters offset:0 atIndex:8];
      [enc setBuffer:s.cbuf offset:0 atIndex:9];
      [enc setBuffer:recB1Buf offset:0 atIndex:10];
      [enc setBuffer:midWBuf offset:0 atIndex:11];
      [enc setBuffer:s.hits offset:0 atIndex:12];
      [enc setBuffer:cenWBuf offset:0 atIndex:14];
      [enc setBuffer:ahiRbBuf offset:0 atIndex:15];
      [enc dispatchThreads:MTLSizeMake(nPieces, subA, 1) threadsPerThreadgroup:MTLSizeMake(std::min<u32>(256, nPieces), 1, 1)];
      // 6. deferred full tests (bindings 0..12 are still those of v2_agen)
      [enc setComputePipelineState:pso.v2indirect];
      [enc setBuffer:s.counters offset:0 atIndex:8];
      [enc setBytes:&va length:sizeof va atIndex:1];
      [enc setBuffer:s.ind offset:0 atIndex:13];
      [enc dispatchThreads:MTLSizeMake(1, 1, 1) threadsPerThreadgroup:MTLSizeMake(1, 1, 1)];
      [enc setComputePipelineState:pso.v2check];
      [enc dispatchThreadgroupsWithIndirectBuffer:s.ind indirectBufferOffset:0 threadsPerThreadgroup:MTLSizeMake(256, 1, 1)];
    };
    auto submit_range = [&](Slot2& s, u64 j0, u64 j1) {
      memset(s.counters.contents, 0, 16 * 4);
      id<MTLCommandBuffer> cb = [g->queue commandBuffer];
      id<MTLComputeCommandEncoder> enc = [cb computeCommandEncoder];
      for (u64 j = j0; j < j1; j++) encode_batch(enc, s, mine[j]);
      [enc endEncoding];
      [cb commit];
      s.cb = cb;
      s.j0 = j0;
      s.j1 = j1;
    };
    // synchronous re-run of [j0, j1) after a failure: halves until single batches, 3 tries each
    std::function<void(Slot2&, u64, u64, int)> redo = [&](Slot2& s, u64 j0, u64 j1, int tries) {
      submit_range(s, j0, j1);
      if (harvest(s)) return;
      if (j1 - j0 > 1) {
        u64 mid = j0 + (j1 - j0) / 2;
        redo(s, j0, mid, 3);
        redo(s, mid, j1, 3);
      } else if (tries > 1) {
        redo(s, j0, j1, tries - 1);
      } else {
        throw std::runtime_error("GPU command buffer keeps failing on a single batch");
      }
    };
    auto settle = [&](Slot2& s) {
      u64 j0 = s.j0, j1 = s.j1;
      if (!harvest(s)) redo(s, j0, j1, 3);
    };
    auto lastReport = std::chrono::steady_clock::now();
    int cur = 0;
    const double targetSeconds = 0.25;
    for (u64 b0 = 0; b0 < nm;) {
      Slot2& s = slots[cur];
      settle(s);
      if (lastTimePerBatch > 0)
        G = (u64)std::max(1.0, std::min(4096.0, targetSeconds / lastTimePerBatch));
      u64 b1 = std::min(nm, b0 + G);
      submit_range(s, b0, b1);
      b0 = b1;
      cur = (cur + 1) % NS;
      auto now = std::chrono::steady_clock::now();
      if (std::chrono::duration<double>(now - lastReport).count() > (verbose ? 5.0 : 30.0)) {
        double el = std::chrono::duration<double>(now - t0).count();
        double frac = (double)b0 / (double)nm;
        fprintf(stderr, "    L=%u v2  %.2f%% of %llu batches  %.3g nodes/s  elapsed %.0fs  eta %.0fs  (%llu batches/buffer)\n",
                p2.base.L, 100.0 * frac, (unsigned long long)nm, (double)st.nodes / std::max(el, 1e-9), el,
                el / std::max(frac, 1e-12) - el, (unsigned long long)G);
        lastReport = now;
      }
    }
    for (auto& s : slots) settle(s);
    st.seconds = std::chrono::duration<double>(std::chrono::steady_clock::now() - t0).count();
    if (verbose)
      fprintf(stderr, "    gpu-v2: %llu batches (%llu per command buffer), table <= %llu entries, %u buckets, "
                      "subB=%u subA=%u, %.3g candidates passed the prefilter  %.3g nodes/s\n",
              (unsigned long long)nb, (unsigned long long)G, (unsigned long long)maxEnts, nBuckets, subB, subA,
              (double)prefPass, st.nodes / std::max(st.seconds, 1e-9));
    return st;
  }
}
