// gpu_cuda.cpp - NVIDIA CUDA engine (driver API + NVRTC).  Mirrors gpu_metal.mm: the kernels
// (core.h + kernels.cu) are compiled at run time with the constants of each search baked in, the
// tables are built on the CPU and uploaded, and slots of streams overlap CPU-side preparation with
// GPU work.  A GPU that drives a display has a kernel watchdog, and on CUDA a killed kernel takes the
// whole context down (unlike a failed Metal command buffer), so every launch is sized from measured
// GPU time to stay near 0.25 s.
#include <cuda.h>
#include <nvrtc.h>

#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <map>
#include <memory>
#include <stdexcept>
#include <string>
#include <thread>
#include <vector>

#include "gpu.h"

// core.h + kernels.cu, generated by the Makefile
static const char* kKernelSource =
#include "kernels_cuda_src.inc"
    ;

static void ck(CUresult r, const char* what) {
  if (r != CUDA_SUCCESS) {
    const char* s = nullptr;
    cuGetErrorString(r, &s);
    throw std::runtime_error(std::string("CUDA error in ") + what + ": " + (s ? s : "unknown"));
  }
}
#define CK(x) ck((x), #x)

struct KArgs {
  uint32_t nSuffix, nPrefix, hitCap, candCap;
};
struct V2Args {
  uint64_t c0;
  uint32_t ww, nBuckets, nB1, subB, nPieces, subA, hitCap, candCap, nBlocks, pad;
};

struct Kernels {
  CUmodule mod = nullptr;
  CUfunction search, check, v2zero, v2bgen, scanLocal, scanBlocks, scanAdd, v2agen, v2check, layout;
  CUdeviceptr prm = 0;  // __constant__ Params c_prm
};

struct GpuEngine {
  CUdevice dev = 0;
  CUcontext ctx = nullptr;
  int major = 0, minor = 0, sms = 0;
  bool integrated = false;  // GPU shares system memory (e.g. GB10): use managed memory throughout
  std::string name;
  bool verbose = false;
  std::map<std::string, Kernels> cache;  // specialised modules by #define prelude
  CUdeviceptr offs = 0, ents = 0;        // v1 table, reused across lengths
  size_t offsCap = 0, entsCap = 0;
};

namespace {
// On an integrated GPU (GB10) ordinary device allocations are mapped with small pages: random
// reads across a multi-GB table run ~35x slower than from managed memory (measured 7e7 vs 2.6e9
// reads/s over 9 GB), so the big v1 table lives in managed memory there.  Everything else (small
// or atomics-heavy: v2 batch tables are ~15% slower in managed memory) uses device memory.
bool g_managed = false;
void dalloc(CUdeviceptr* p, size_t n, bool big = false) {
  if (g_managed && big)
    CK(cuMemAllocManaged(p, n, CU_MEM_ATTACH_GLOBAL));
  else
    CK(cuMemAlloc(p, n));
}
// device memory
struct DBuf {
  CUdeviceptr p = 0;
  size_t n = 0;
  void alloc(size_t bytes) {
    release();
    n = std::max<size_t>(bytes, 16);
    dalloc(&p, n);
  }
  void release() {
    if (p) cuMemFree(p);
    p = 0;
    n = 0;
  }
  ~DBuf() { release(); }
};
// pinned host memory (async copies)
struct HBuf {
  void* p = nullptr;
  void alloc(size_t bytes) {
    release();
    CK(cuMemHostAlloc(&p, std::max<size_t>(bytes, 16), 0));
  }
  void release() {
    if (p) cuMemFreeHost(p);
    p = nullptr;
  }
  ~HBuf() { release(); }
};
template <class T>
void upload(DBuf& b, const std::vector<T>& v) {
  b.alloc(v.size() * sizeof(T));
  if (!v.empty()) CK(cuMemcpyHtoD(b.p, v.data(), v.size() * sizeof(T)));
}
double since(std::chrono::steady_clock::time_point t) {
  return std::chrono::duration<double>(std::chrono::steady_clock::now() - t).count();
}
unsigned blocks_for(uint64_t n, unsigned per = 256) { return (unsigned)std::max<uint64_t>(1, (n + per - 1) / per); }
void launch(CUfunction f, unsigned blocks, unsigned threads, CUstream s, void** args) {
  CK(cuLaunchKernel(f, blocks, 1, 1, threads, 1, 1, 0, s, args, nullptr));
}
}  // namespace

// Constants of this search baked into the kernel source (same set as the Metal engine).
static std::string spec_prelude(const Params& p) {
  char buf[768];
  snprintf(buf, sizeof buf,
           "#define SPEC_Q %u\n#define SPEC_P %u\n#define SPEC_C %u\n#define SPEC_RHO %lluull\n#define SPEC_QBITS %u\n"
           "#define SPEC_GMODE %u\n#define SPEC_T %u\n#define SPEC_UEFF %u\n#define SPEC_NSEG %u\n#define SPEC_REVR %u\n"
           "#define SPEC_R %u\n#define SPEC_TP %u\n#define SPEC_V2U %u\n#define SPEC_R0 %u\n",
           p.Q, p.P, p.c, (unsigned long long)p.rho, p.qbits, p.gmode, p.t, p.ueff, p.nseg, p.revR, p.r, p.tp, p.v2u,
           p.r0);
  return buf;
}

// NVRTC: a cubin for the device's own architecture, or PTX for the driver to JIT if NVRTC does not
// know that architecture.
static std::vector<char> nvrtc_compile(GpuEngine* g, const std::string& src) {
  for (int pass = 0; pass < 2; pass++) {
    nvrtcProgram prog;
    if (nvrtcCreateProgram(&prog, src.c_str(), "dbpal_kernels.cu", 0, nullptr, nullptr) != NVRTC_SUCCESS)
      throw std::runtime_error("nvrtcCreateProgram failed");
    std::string arch = std::string("--gpu-architecture=") + (pass == 0 ? "sm_" : "compute_") +
                       std::to_string(g->major) + std::to_string(g->minor);
    const char* opts[] = {arch.c_str(), "--std=c++17"};
    nvrtcResult r = nvrtcCompileProgram(prog, 2, opts);
    if (r != NVRTC_SUCCESS) {
      size_t n = 0;
      nvrtcGetProgramLogSize(prog, &n);
      std::string log(n, '\0');
      nvrtcGetProgramLog(prog, &log[0]);
      nvrtcDestroyProgram(&prog);
      if (pass == 0 && r == NVRTC_ERROR_INVALID_OPTION) continue;  // unknown sm_XY: fall back to PTX
      throw std::runtime_error("NVRTC compile failed:\n" + log);
    }
    std::vector<char> out;
    size_t n = 0;
    if (pass == 0) {
      nvrtcGetCUBINSize(prog, &n);
      out.resize(n);
      nvrtcGetCUBIN(prog, out.data());
    } else {
      nvrtcGetPTXSize(prog, &n);
      out.resize(n);
      nvrtcGetPTX(prog, out.data());
    }
    nvrtcDestroyProgram(&prog);
    return out;
  }
  throw std::runtime_error("NVRTC: no usable architecture");
}

static Kernels& kernels_for(GpuEngine* g, const std::string& pre) {
  auto it = g->cache.find(pre);
  if (it != g->cache.end()) return it->second;
  auto t0 = std::chrono::steady_clock::now();
  std::string extra;  // DBPAL_CUDA_DEFINES="NAME=VALUE;...": tuning knobs (see kernels.cu)
  if (const char* e = std::getenv("DBPAL_CUDA_DEFINES")) {
    std::string d = e;
    for (size_t a = 0; a < d.size();) {
      size_t b = d.find(';', a);
      if (b == std::string::npos) b = d.size();
      std::string kv = d.substr(a, b - a);
      size_t eq = kv.find('=');
      if (!kv.empty()) extra += "#define " + (eq == std::string::npos ? kv : kv.substr(0, eq) + " " + kv.substr(eq + 1)) + "\n";
      a = b + 1;
    }
  }
  std::string src = "#define NLIMB " + std::to_string(NLIMB) + "\n" + extra + pre + kKernelSource;
  std::vector<char> image = nvrtc_compile(g, src);
  Kernels k;
  CK(cuModuleLoadData(&k.mod, image.data()));
  auto fn = [&](const char* name) {
    CUfunction f;
    CK(cuModuleGetFunction(&f, k.mod, name));
    return f;
  };
  k.search = fn("search_nodes");
  k.check = fn("check_cands");
  k.v2zero = fn("v2_zero");
  k.v2bgen = fn("v2_bgen");
  k.scanLocal = fn("scan_local");
  k.scanBlocks = fn("scan_blocks");
  k.scanAdd = fn("scan_add");
  k.v2agen = fn("v2_agen");
  k.v2check = fn("v2_check");
  k.layout = fn("layout_check");
  size_t sz = 0;
  CK(cuModuleGetGlobal(&k.prm, &sz, k.mod, "c_prm"));
  if (sz != sizeof(Params)) throw std::runtime_error("CUDA: Params size mismatch");
  if (g->verbose) fprintf(stderr, "    compiled specialised CUDA kernels in %.2fs\n", since(t0));
  return g->cache[pre] = k;
}

GpuEngine* gpu_create(bool verbose) {
  try {
    if (cuInit(0) != CUDA_SUCCESS) return nullptr;
    int count = 0;
    if (cuDeviceGetCount(&count) != CUDA_SUCCESS || count == 0) return nullptr;
    auto g = std::make_unique<GpuEngine>();
    g->verbose = verbose;
    int ord = 0;
    if (const char* e = std::getenv("DBPAL_CUDA_DEVICE")) ord = std::atoi(e);
    CK(cuDeviceGet(&g->dev, ord));
    char name[256] = {0};
    CK(cuDeviceGetName(name, sizeof name, g->dev));
    CK(cuDeviceGetAttribute(&g->major, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MAJOR, g->dev));
    CK(cuDeviceGetAttribute(&g->minor, CU_DEVICE_ATTRIBUTE_COMPUTE_CAPABILITY_MINOR, g->dev));
    CK(cuDeviceGetAttribute(&g->sms, CU_DEVICE_ATTRIBUTE_MULTIPROCESSOR_COUNT, g->dev));
    int integ = 0, managed = 0;
    cuDeviceGetAttribute(&integ, CU_DEVICE_ATTRIBUTE_INTEGRATED, g->dev);
    cuDeviceGetAttribute(&managed, CU_DEVICE_ATTRIBUTE_CONCURRENT_MANAGED_ACCESS, g->dev);
    g->integrated = integ && managed;
    if (const char* e = std::getenv("DBPAL_CUDA_MANAGED")) g->integrated = std::atoi(e) != 0;
    g_managed = g->integrated;
    CK(cuDevicePrimaryCtxRetain(&g->ctx, g->dev));
    CK(cuCtxSetCurrent(g->ctx));
    auto t0 = std::chrono::steady_clock::now();
    Kernels& k = kernels_for(g.get(), "");
    // layout check: host and device must agree on the Params struct
    Params p{};
    p.Q = 7;
    p.seg[1].LQ = 1234;
    p.qpow[3] = 0xabcdef12345ull;
    p.centerDig[1] = 77;
    p.Wmax.l[1] = 0x55aa55aa11ull;
    p.recLoN = 4242;
    CK(cuMemcpyHtoD(k.prm, &p, sizeof p));
    DBuf out;
    out.alloc(64);
    void* args[] = {&out.p};
    launch(k.layout, 1, 1, nullptr, args);
    CK(cuCtxSynchronize());
    uint32_t o[16];
    CK(cuMemcpyDtoH(o, out.p, 64));
    bool ok = o[0] == sizeof(Params) && o[1] == sizeof(SegInfo) && o[2] == sizeof(NumQ) && o[3] == sizeof(FastDiv) &&
              o[4] == 7 && o[5] == 1234 && o[6] == (uint32_t)(p.qpow[3] & 0xffffffffu) && o[7] == 77 &&
              o[8] == (uint32_t)(p.Wmax.l[1] & 0xffffffffu) && o[9] == 4242;
    if (!ok) {
      fprintf(stderr, "CUDA layout mismatch: sizeof(Params) host %zu device %u\n", sizeof(Params), o[0]);
      return nullptr;
    }
    g->name = std::string("gpu: ") + name + " (CUDA sm_" + std::to_string(g->major) + std::to_string(g->minor) +
              (g->integrated ? ", unified memory)" : ")");
    if (verbose) fprintf(stderr, "# CUDA kernels compiled in %.2fs; layout check OK\n", since(t0));
    return g.release();
  } catch (std::exception& e) {
    fprintf(stderr, "%s\n", e.what());
    return nullptr;
  }
}

const char* gpu_name(GpuEngine* g) { return g ? g->name.c_str() : "none"; }

void gpu_destroy(GpuEngine* g) {
  if (!g) return;
  cuCtxSetCurrent(g->ctx);
  for (auto& kv : g->cache) cuModuleUnload(kv.second.mod);
  if (g->offs) cuMemFree(g->offs);
  if (g->ents) cuMemFree(g->ents);
  cuDevicePrimaryCtxRelease(g->dev);
  delete g;
}

// =============================================================================================
// v1 (one big table) on the GPU
// =============================================================================================
RunStats run_gpu(GpuEngine* g, const Plan& pl, int threads, std::vector<NumQ>& found, double* tableSeconds,
                 bool verbose) {
  CK(cuCtxSetCurrent(g->ctx));
  const Params& p = pl.prm;
  RunStats st;
  // ---- table: built on the CPU, uploaded to device memory (large pages: random probes) ------
  size_t ob = table_offs_bytes(pl), eb = table_ents_bytes(pl);
  double tb = 0;
  if (g->offsCap < ob) {
    if (g->offs) cuMemFree(g->offs);
    g->offs = 0;
    dalloc(&g->offs, std::max<size_t>(ob, 16), true);
    g->offsCap = ob;
  }
  if (g->entsCap < eb) {
    if (g->ents) cuMemFree(g->ents);
    g->ents = 0;
    dalloc(&g->ents, std::max<size_t>(eb, 16), true);
    g->entsCap = eb;
  }
  if (g->integrated) {  // unified memory: the CPU builds the table in place (as with Metal)
    TableView tv{(u32*)(uintptr_t)g->offs, (u64*)(uintptr_t)g->ents};
    tb = build_table(pl, tv, threads);
  } else {  // discrete GPU: build in host memory, upload
    std::unique_ptr<u32[]> hoffs(new u32[ob / sizeof(u32) + 1]);
    std::unique_ptr<u64[]> hents(new u64[eb / sizeof(u64) + 1]);
    TableView tv{hoffs.get(), hents.get()};
    tb = build_table(pl, tv, threads);
    auto tu = std::chrono::steady_clock::now();
    if (ob) CK(cuMemcpyHtoD(g->offs, hoffs.get(), ob));
    if (eb) CK(cuMemcpyHtoD(g->ents, hents.get(), eb));
    tb += since(tu);
  }
  if (tableSeconds) *tableSeconds = tb;

  auto t0 = std::chrono::steady_clock::now();
  // ---- split the outer digits: prefixes (CPU, with pruning) x suffixes (GPU grid) ------------
  u32 ks = 0;
  u64 nSuffix = 1;
  const u64 suffixMax = p.gmode ? 1000 : 600000;
  while (ks + 1 < p.k && nSuffix * p.P <= suffixMax) {
    nSuffix *= p.P;
    ks++;
  }
  u32 k0 = p.k - ks;
  std::vector<NumQ> suffix(nSuffix);
  for (u64 x = 0; x < nSuffix; x++) {
    NumQ acc{};
    u64 r = x;
    for (int i = (int)p.k - 1; i >= (int)k0; i--) {
      u32 d = (u32)(r % p.P);
      r /= p.P;
      if (d) acc = nq_add(acc, pl.outerW[(size_t)i * p.P + d], p.rho);
    }
    suffix[x] = acc;
  }
  Kernels& K = kernels_for(g, spec_prelude(p));
  CK(cuMemcpyHtoD(K.prm, &p, sizeof(Params)));
  DBuf suffixB, revB, hiB, loB;
  upload(suffixB, suffix);
  upload(revB, pl.revtab);
  upload(hiB, pl.recHi);
  upload(loB, pl.recLo);

  const uint32_t hitCap = 4096;
  const uint32_t candCap = 1u << 24;  // deferred candidates per launch (12 bytes each)
  double candRate = pl.nodesEst > 0 ? pl.candsEst / pl.nodesEst : 0.0;
  double nodesMax = std::min(double(1ull << 27), 0.5 * candCap / std::max(candRate, 1e-9));
  uint32_t perBatchMax = (uint32_t)std::max<double>(1.0, std::floor(nodesMax / (double)nSuffix));
  // launches are sized from measured time; the first ones are small
  uint32_t perBatch = (uint32_t)std::max<double>(1.0, std::min<double>(perBatchMax, (double)(1u << 22) / nSuffix));
  const double targetSeconds = 0.25;
  double secPerNode = 0;
  const unsigned checkBlocks = (unsigned)std::max(1, 8 * g->sms);

  struct Slot {
    CUstream stream = nullptr;
    CUevent e0 = nullptr, e1 = nullptr;
    HBuf hprefix, hcount;
    DBuf prefix, counters, hits, cands;
    uint32_t nPrefix = 0;
    u64 nodes = 0;
    bool busy = false;
  };
  const int NS = 3;
  Slot slots[NS];
  for (auto& s : slots) {
    CK(cuStreamCreate(&s.stream, CU_STREAM_NON_BLOCKING));
    CK(cuEventCreate(&s.e0, CU_EVENT_DEFAULT));
    CK(cuEventCreate(&s.e1, CU_EVENT_DEFAULT));
    s.hprefix.alloc((size_t)perBatchMax * sizeof(NumQ));
    s.hcount.alloc(16 * sizeof(uint32_t));
    s.prefix.alloc((size_t)perBatchMax * sizeof(NumQ));
    s.counters.alloc(16 * sizeof(uint32_t));
    s.hits.alloc((size_t)hitCap * sizeof(NumQ));
    s.cands.alloc((size_t)candCap * 12);
  }
  u64 deferred = 0;
  std::vector<NumQ> hbuf(hitCap);

  auto harvest = [&](Slot& s) {
    if (!s.busy) return;
    CK(cuStreamSynchronize(s.stream));
    const uint32_t* c = (const uint32_t*)s.hcount.p;
    uint32_t nh = c[0];
    if (nh > hitCap) throw std::runtime_error("GPU hit buffer overflow");
    if (nh) {
      CK(cuMemcpyDtoH(hbuf.data(), s.hits.p, nh * sizeof(NumQ)));
      found.insert(found.end(), hbuf.begin(), hbuf.begin() + nh);
    }
    st.probes += c[1];
    st.cands += c[2];
    st.overflow += c[3];
    deferred += std::min(c[4], candCap);
    st.nodes += s.nodes;
    float ms = 0;
    if (cuEventElapsedTime(&ms, s.e0, s.e1) == CUDA_SUCCESS && ms > 0 && s.nodes) secPerNode = 1e-3 * ms / s.nodes;
    s.busy = false;
  };
  auto submit = [&](Slot& s) {
    KArgs ka{(uint32_t)nSuffix, s.nPrefix, hitCap, candCap};
    CK(cuMemcpyHtoDAsync(s.prefix.p, s.hprefix.p, (size_t)s.nPrefix * sizeof(NumQ), s.stream));
    CK(cuMemsetD32Async(s.counters.p, 0, 16, s.stream));
    CK(cuEventRecord(s.e0, s.stream));
    void* a1[] = {&s.prefix.p, &suffixB.p, &revB.p, &g->offs, &g->ents, &hiB.p, &loB.p,
                  &s.counters.p, &s.hits.p, &ka, &s.cands.p};
    launch(K.search, blocks_for(nSuffix * s.nPrefix), 256, s.stream, a1);
    void* a2[] = {&s.prefix.p, &suffixB.p, &revB.p, &hiB.p, &loB.p, &s.counters.p, &s.hits.p, &ka, &s.cands.p};
    launch(K.check, checkBlocks, 256, s.stream, a2);
    CK(cuEventRecord(s.e1, s.stream));
    CK(cuMemcpyDtoHAsync(s.hcount.p, s.counters.p, 16 * sizeof(uint32_t), s.stream));
    s.nodes = nSuffix * (u64)s.nPrefix;
    s.busy = true;
  };
  auto resize = [&]() {
    if (secPerNode > 0)
      perBatch = (uint32_t)std::max<double>(
          1.0, std::min<double>(perBatchMax, targetSeconds / (secPerNode * (double)nSuffix)));
  };

  int cur = 0;
  double totalPrefix = (double)pl.topDigits.size() * std::pow((double)p.P, (double)k0 - 1);
  u64 emitted = 0;
  auto lastReport = std::chrono::steady_clock::now();
  slots[cur].nPrefix = 0;
  u64 seenPrefix = 0;
  st.pruned += gen_prefixes(pl, k0, [&](const NumQ& C) {
    if (seenPrefix++ % pl.partN != pl.partI) return;  // --part i/n: interleaved prefixes
    Slot& s = slots[cur];
    ((NumQ*)s.hprefix.p)[s.nPrefix++] = C;
    emitted++;
    if (s.nPrefix >= perBatch) {
      submit(s);
      cur = (cur + 1) % NS;
      harvest(slots[cur]);
      resize();
      slots[cur].nPrefix = 0;
      auto now = std::chrono::steady_clock::now();
      if (verbose || std::chrono::duration<double>(now - lastReport).count() > 30) {
        double el = since(t0);
        double frac = emitted * (double)pl.partN / totalPrefix;
        fprintf(stderr, "    L=%u  %.2f%% of prefixes  %.3g nodes/s  elapsed %.0fs  eta %.0fs\n", pl.L,
                100.0 * frac, (double)st.nodes / std::max(el, 1e-9), el, el / std::max(frac, 1e-12) - el);
        lastReport = now;
      }
    }
  });
  if (slots[cur].nPrefix) submit(slots[cur]);
  for (auto& s : slots) harvest(s);
  for (auto& s : slots) {
    cuEventDestroy(s.e0);
    cuEventDestroy(s.e1);
    cuStreamDestroy(s.stream);
  }
  st.seconds = since(t0);
  if (verbose)
    fprintf(stderr, "    gpu: k0=%u ks=%u suffix=%llu perBatch<=%u deferred=%.3g  %.3g nodes/s\n", k0, ks,
            (unsigned long long)nSuffix, perBatchMax, (double)deferred, st.nodes / std::max(st.seconds, 1e-9));
  return st;
}

// =============================================================================================
// v2 on the GPU
// =============================================================================================
RunStats run_gpu2(GpuEngine* g, const Plan2& p2, int threads, std::vector<NumQ>& found, bool verbose) {
  CK(cuCtxSetCurrent(g->ctx));
  const Params& p = p2.base.prm;
  RunStats st;
  auto t0 = std::chrono::steady_clock::now();
  Kernels& K = kernels_for(g, spec_prelude(p));
  CK(cuMemcpyHtoD(K.prm, &p, sizeof(Params)));
  const u64 Qr = p.Qr, w = p.w, nb = (Qr + w - 1) / w;
  std::vector<u64> mine;  // --part i/n: interleaved batches
  for (u64 bi = p2.base.partI; bi < nb; bi += p2.base.partN) mine.push_back(bi);
  const u64 nm = mine.size();
  const uint32_t nBuckets = (uint32_t)(w * p.qpow[p.tp]);
  const uint32_t nBlocks = (nBuckets + 2 + 1023) / 1024;
  // exact size of every batch table (so the entry buffer can never overflow)
  std::vector<u64> bcount(nm, 0);
  {
    std::vector<std::thread> th;
    int T = std::max(1, threads);
    for (int t = 0; t < T; t++)
      th.emplace_back([&, t] {
        for (u64 j = t; j < nm; j += T) {
          u64 bi = mine[j];
          u64 c0 = bi * w, ww = std::min(w, Qr - c0), tot = 0;
          for (u32 b1 = 0; b1 < p.nB1; b1++) {
            u64 lo = (c0 + Qr - (p2.b1V[b1] / p.qpow[p.r0]) % Qr) % Qr;
            if (lo + ww <= Qr)
              tot += p2.b2Offs[lo + ww] - p2.b2Offs[lo];
            else
              tot += (p2.b2Offs[Qr] - p2.b2Offs[lo]) + (p2.b2Offs[lo + ww - Qr] - p2.b2Offs[0]);
          }
          bcount[j] = tot;
        }
      });
    for (auto& x : th) x.join();
  }
  u64 maxEnts = 1;
  for (u64 c : bcount) maxEnts = std::max(maxEnts, c);
  // static data
  DBuf revB, ahiB, ahiRbB, aloCB, aloOffsB, b1VB, recB1B, b2VB, b2IdxB, b2OffsB, midWB, cenWB;
  upload(revB, p2.base.revtab);
  upload(ahiB, p2.ahi);
  std::vector<u64> ahiRb(p2.ahi.size());  // class bases only: cheap per-batch screening of pieces
  for (size_t i = 0; i < p2.ahi.size(); i++) ahiRb[i] = p2.ahi[i].Rr;
  upload(ahiRbB, ahiRb);
  upload(aloCB, p2.aloC);
  upload(aloOffsB, p2.aloOffs);
  upload(b1VB, p2.b1V);
  upload(recB1B, p2.recB1);
  upload(b2VB, p2.b2V);
  upload(b2IdxB, p2.b2Idx);
  upload(b2OffsB, p2.b2Offs);
  upload(midWB, p2.base.midW);
  upload(cenWB, p2.base.cenW);
  const uint32_t hitCap = 4096, candCap = 1u << 24;
  const uint32_t nPieces = (uint32_t)p2.ahi.size();
  const uint32_t subB = (uint32_t)std::max<u64>(1, (65536 + p.nB1 - 1) / p.nB1);
  const uint32_t subA = (uint32_t)std::max<u64>(1, (65536 + nPieces - 1) / nPieces);
  const unsigned checkBlocks = (unsigned)std::max(1, 8 * g->sms);

  struct Slot2 {
    CUstream stream = nullptr;
    CUevent e0 = nullptr, e1 = nullptr;
    DBuf A, blk, ents, cbuf, counters, hits;
    HBuf hcount;
    u64 j0 = 0, j1 = 0;  // batches (indices into `mine`) in flight
    bool busy = false;
  };
  const int NS = 2;
  Slot2 slots[NS];
  for (auto& s : slots) {
    CK(cuStreamCreate(&s.stream, CU_STREAM_NON_BLOCKING));
    CK(cuEventCreate(&s.e0, CU_EVENT_DEFAULT));
    CK(cuEventCreate(&s.e1, CU_EVENT_DEFAULT));
    s.A.alloc(((size_t)nBuckets + 2) * 4);
    s.blk.alloc((size_t)nBlocks * 4 + 16);
    s.ents.alloc((size_t)maxEnts * 8);
    s.cbuf.alloc((size_t)candCap * 16);
    s.counters.alloc(16 * 4);
    s.hits.alloc((size_t)hitCap * sizeof(NumQ));
    s.hcount.alloc(16 * 4);
  }
  u64 prefPass = 0;
  double lastTimePerBatch = 0;
  std::vector<NumQ> hbuf(hitCap);
  auto harvest = [&](Slot2& s) {
    if (!s.busy) return;
    CK(cuStreamSynchronize(s.stream));
    const uint32_t* c = (const uint32_t*)s.hcount.p;
    if (c[0] > hitCap) throw std::runtime_error("GPU hit buffer overflow");
    if (c[0]) {
      CK(cuMemcpyDtoH(hbuf.data(), s.hits.p, c[0] * sizeof(NumQ)));
      found.insert(found.end(), hbuf.begin(), hbuf.begin() + c[0]);
    }
    st.probes += c[1];
    st.cands += c[2];
    st.overflow += c[3];
    st.nodes += c[5];
    prefPass += c[6];
    float ms = 0;
    if (cuEventElapsedTime(&ms, s.e0, s.e1) == CUDA_SUCCESS && ms > 0 && s.j1 > s.j0)
      lastTimePerBatch = 1e-3 * ms / (double)(s.j1 - s.j0);
    s.busy = false;
  };
  uint32_t zero = 0, one = 1;
  auto encode_batch = [&](Slot2& s, u64 bi, V2Args& va) {
    va.c0 = bi * w;
    va.ww = (uint32_t)std::min(w, Qr - va.c0);
    va.nBuckets = nBuckets;
    va.nB1 = p.nB1;
    va.subB = subB;
    va.nPieces = nPieces;
    va.subA = subA;
    va.hitCap = hitCap;
    va.candCap = candCap;
    va.nBlocks = nBlocks;
    va.pad = 0;
    // kernel arguments are copied at launch, so va may change for the next batch
    void* az[] = {&s.A.p, &va, &s.counters.p};
    launch(K.v2zero, blocks_for(nBuckets + 2), 256, s.stream, az);  // 1. clear counts + deferred count
    void* ab0[] = {&b1VB.p, &b2VB.p, &b2IdxB.p, &b2OffsB.p, &s.A.p, &s.ents.p, &va, &zero};
    launch(K.v2bgen, blocks_for((u64)p.nB1 * subB), 256, s.stream, ab0);  // 2. count middles per bucket
    void* as1[] = {&s.A.p, &s.blk.p, &va};
    launch(K.scanLocal, nBlocks, 256, s.stream, as1);  // 3. inclusive scan
    void* as2[] = {&s.blk.p, &va};
    launch(K.scanBlocks, 1, 1024, s.stream, as2);
    void* as3[] = {&s.A.p, &s.blk.p, &va};
    launch(K.scanAdd, blocks_for(nBuckets + 2), 256, s.stream, as3);
    void* ab1[] = {&b1VB.p, &b2VB.p, &b2IdxB.p, &b2OffsB.p, &s.A.p, &s.ents.p, &va, &one};
    launch(K.v2bgen, blocks_for((u64)p.nB1 * subB), 256, s.stream, ab1);  // 4. scatter middles
    void* aa[] = {&ahiB.p, &aloCB.p, &aloOffsB.p, &s.A.p, &s.ents.p, &revB.p, &s.counters.p, &s.cbuf.p,
                  &recB1B.p, &midWB.p, &s.hits.p, &cenWB.p, &ahiRbB.p, &va};
    launch(K.v2agen, blocks_for((u64)nPieces * subA), 256, s.stream, aa);  // 5. outer parts: probe
    void* ac[] = {&ahiB.p, &aloCB.p, &revB.p, &s.counters.p, &s.cbuf.p, &recB1B.p, &midWB.p, &s.hits.p, &cenWB.p, &va};
    launch(K.v2check, checkBlocks, 256, s.stream, ac);  // 6. deferred full tests
  };
  auto submit_range = [&](Slot2& s, u64 j0, u64 j1) {
    CK(cuMemsetD32Async(s.counters.p, 0, 16, s.stream));
    CK(cuEventRecord(s.e0, s.stream));
    V2Args va{};
    for (u64 j = j0; j < j1; j++) encode_batch(s, mine[j], va);
    CK(cuEventRecord(s.e1, s.stream));
    CK(cuMemcpyDtoHAsync(s.hcount.p, s.counters.p, 16 * 4, s.stream));
    s.j0 = j0;
    s.j1 = j1;
    s.busy = true;
  };
  auto lastReport = std::chrono::steady_clock::now();
  int cur = 0;
  const double targetSeconds = 0.25;
  u64 G = 1;  // batches per submission: measured, then sized for ~targetSeconds
  for (u64 b0 = 0; b0 < nm;) {
    Slot2& s = slots[cur];
    harvest(s);
    if (lastTimePerBatch > 0) G = (u64)std::max(1.0, std::min(4096.0, targetSeconds / lastTimePerBatch));
    u64 b1 = std::min(nm, b0 + G);
    submit_range(s, b0, b1);
    b0 = b1;
    cur = (cur + 1) % NS;
    auto now = std::chrono::steady_clock::now();
    if (std::chrono::duration<double>(now - lastReport).count() > (verbose ? 5.0 : 30.0)) {
      double el = since(t0);
      double frac = (double)b0 / (double)nm;
      fprintf(stderr, "    L=%u v2  %.2f%% of %llu batches  %.3g nodes/s  elapsed %.0fs  eta %.0fs  (%llu batches/launch group)\n",
              p2.base.L, 100.0 * frac, (unsigned long long)nm, (double)st.nodes / std::max(el, 1e-9), el,
              el / std::max(frac, 1e-12) - el, (unsigned long long)G);
      lastReport = now;
    }
  }
  for (auto& s : slots) harvest(s);
  for (auto& s : slots) {
    cuEventDestroy(s.e0);
    cuEventDestroy(s.e1);
    cuStreamDestroy(s.stream);
  }
  st.seconds = since(t0);
  if (verbose)
    fprintf(stderr, "    gpu-v2: %llu batches (%llu per launch group), table <= %llu entries, %u buckets, "
                    "subB=%u subA=%u, %.3g candidates passed the prefilter  %.3g nodes/s\n",
            (unsigned long long)nb, (unsigned long long)G, (unsigned long long)maxEnts, nBuckets, subB, subA,
            (double)prefPass, st.nodes / std::max(st.seconds, 1e-9));
  return st;
}
