#!/usr/bin/env python3
"""Summarise results/ against the OEIS: writes RESULTS.md (and prints it).

For every base pair with a completed search, lists the certified bound, the terms beyond the
OEIS data (new terms) and the consequences for the prime sequence (new terms or a new lower
bound for the next term).
"""
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import oeis  # noqa: E402
from campaign import complete_lengths, log_entries  # noqa: E402

RES = os.path.join(ROOT, "results")


def sci(n):
    s = f"{float(n):.3e}"
    m, e = s.split("e")
    return f"{m}·10^{int(e)}"


def bound_for(b1, b2):
    """(P, L, P^L, hours) for the longest complete prefix of lengths (all-palindrome searches)."""
    rs = [r for r in log_entries() if sorted(r["bases"]) == sorted([b1, b2]) and not r["primesOnly"]]
    if not rs:
        return None
    P = rs[0]["P"]
    Ls = complete_lengths(rs)
    L = 0
    while L + 1 in Ls:
        L += 1
    secs = sum(r.get("seconds", 0) + r.get("tableSeconds", 0) for r in rs if r["L"] <= L)
    return P, L, P ** L, secs / 3600


def main():
    fam = oeis.family()
    lines = ["# Results", "",
             "Generated by `tools/report.py` from `results/*.tsv` and `results/search_log.jsonl`.",
             "A bound `N < X` means every length below X was searched completely (logged as done).", ""]
    for fn in sorted(os.listdir(RES)):
        if not (fn.startswith("b") and fn.endswith(".tsv")):
            continue
        b1, b2 = map(int, fn[1:-4].split("_"))
        bnd = bound_for(b1, b2)
        if not bnd or bnd[1] == 0:
            continue
        P, L, lim, hours = bnd
        terms = {}
        for line in open(os.path.join(RES, fn)):
            p = line.rstrip("\n").split("\t")
            if len(p) >= 2 and p[0].isdigit() and int(p[0]) < lim:
                terms[int(p[0])] = p[1] == "1"
        allt = sorted(terms)
        primes = [n for n in allt if terms[n]]
        e_all = fam.get(((b1, b2), False))
        e_pr = fam.get(((b1, b2), True))
        lines.append(f"## Bases {b1} and {b2}")
        lines.append("")
        lines.append(f"* searched: all N < {P}^{L} ≈ {sci(lim)} ({hours:.2f} h of search time logged)")
        lines.append(f"* {len(allt)} numbers palindromic in both bases (incl. 0 if listed), {len(primes)} of them prime")
        for e, mine, label in ((e_all, allt, "all"), (e_pr, primes, "primes")):
            if not e:
                lines.append(f"* {label}: no OEIS sequence in the family")
                continue
            known = sorted(set(oeis.all_terms(e)))
            kb = [n for n in known if n < lim]
            missing = sorted(set(kb) - set(mine))
            new = [n for n in mine if n not in set(known)]
            mx = max(known) if known else 0
            lines.append(f"* **{e['anum']}** ({e['name']}): OEIS lists {len(known)} terms up to {sci(mx) if mx else '-'}; "
                         f"all {len(kb)} below the bound reproduced" + (f" — MISSING {missing}" if missing else ""))
            if new:
                lines.append(f"  * {len(new)} terms not in the OEIS data:")
                for n in new:
                    lines.append(f"    * {n}")
            if label == "primes":
                lines.append(f"  * next term (if any) > {P}^{L} ≈ {sci(lim)}")
        lines.append("")
    text = "\n".join(lines) + "\n"
    with open(os.path.join(ROOT, "RESULTS.md"), "w") as f:
        f.write(text)
    print(text)


if __name__ == "__main__":
    main()
