/* generated from mitm_gpu.m — validated kernel */
static NSString *KERNEL_SRC = @""
"#include <metal_stdlib>\n"
"using namespace metal;\n"
"struct W { ulong d0,d1,d2; };\n"
"struct P {\n"
"  uint b1,b2,s,t,j,je,kdig,odd;\n"
"  ulong Q,QF,c3f;\n"
"  ulong Mb1,Mb2,MQ,MQF;\n"
"  ulong PM0,PM1,PM2, PS0,PS1,PS2, PT0,PT1,PT2, PB0,PB1x,PB2, ST0,ST1,ST2;\n"
"  ulong yh0,yhEnd,G; uint outCap; uint pad;\n"
"};\n"
"static inline ulong divq(ulong x, ulong M, ulong d, thread ulong &r){\n"
"  ulong q=mulhi(x,M); r=x-q*d; if(r>=d){r-=d;q++;} return q; }\n"
"static inline W mkw(ulong a, ulong b, ulong c){ W r; r.d0=a; r.d1=b; r.d2=c; return r; }\n"
"static inline int wcmp(W a, W b){\n"
"  if (a.d2!=b.d2) return a.d2<b.d2?-1:1;\n"
"  if (a.d1!=b.d1) return a.d1<b.d1?-1:1;\n"
"  if (a.d0!=b.d0) return a.d0<b.d0?-1:1; return 0; }\n"
"static inline W wadd(W a, W b){ W r; r.d0=a.d0+b.d0; ulong c0=r.d0<a.d0?1:0;\n"
"  ulong s1=a.d1+b.d1; ulong c1=s1<a.d1?1:0; r.d1=s1+c0; if(r.d1<s1) c1++;\n"
"  r.d2=a.d2+b.d2+c1; return r; }\n"
"static inline W wsub(W a, W b){ W r; r.d0=a.d0-b.d0; ulong br0=a.d0<b.d0?1:0;\n"
"  ulong s1=a.d1-b.d1; ulong br1=a.d1<b.d1?1:0; r.d1=s1-br0; if(s1<br0) br1++;\n"
"  r.d2=a.d2-b.d2-br1; return r; }\n"
"static inline W wsub1(W a){ W r=a; if(r.d0--==0){ if(r.d1--==0) r.d2--; } return r; }\n"
"static inline W waddu(W a, ulong b){ W r=a; r.d0+=b; if(r.d0<b){ if(++r.d1==0) ++r.d2; } return r; }\n"
"static inline W wmulu(W a, ulong m){\n"
"  ulong l0=a.d0*m, h0=mulhi(a.d0,m);\n"
"  ulong l1=a.d1*m, h1=mulhi(a.d1,m);\n"
"  ulong l2=a.d2*m;\n"
"  W r; r.d0=l0; r.d1=l1+h0; ulong c=(r.d1<l1)?1:0; r.d2=l2+h1+c; return r; }\n"
"static inline ulong wdivbig(W num, W den, thread W &rem){\n"
"  W r=mkw(0,0,0); ulong q=0;\n"
"  for (int i=191;i>=0;i--){\n"
"    r.d2=(r.d2<<1)|(r.d1>>63); r.d1=(r.d1<<1)|(r.d0>>63);\n"
"    ulong bit = (i>=128)?((num.d2>>(i-128))&1):(i>=64)?((num.d1>>(i-64))&1):((num.d0>>i)&1);\n"
"    r.d0=(r.d0<<1)|bit;\n"
"    if (wcmp(r,den)>=0){ r=wsub(r,den); if(i<64) q|=(ulong)1<<i; }\n"
"  }\n"
"  rem=r; return q; }\n"
"static inline ulong mod128(ulong hi, ulong lo, ulong m){\n"
"  ulong r=0;\n"
"  for (int i=127;i>=0;i--){\n"
"    ulong top = r>>63; r=(r<<1)|((i>=64)?((hi>>(i-64))&1):((lo>>i)&1));\n"
"    if (top || r>=m) r-=m; }\n"
"  return r; }\n"
"static inline ulong revm(ulong x, uint b, uint d, ulong Mb){\n"
"  ulong r=0;\n"
"  for(uint i=0;i<d;i++){ ulong rem; x=divq(x,Mb,b,rem); r=r*b+rem; }\n"
"  return r; }\n"
"kernel void sweep(device const uint *off [[buffer(0)]],\n"
"                  device const ulong *ent [[buffer(1)]],\n"
"                  constant P &C [[buffer(2)]],\n"
"                  device atomic_uint *outN [[buffer(3)]],\n"
"                  device ulong *outP [[buffer(4)]],\n"
"                  device atomic_uint *stats [[buffer(5)]],\n"
"                  uint tid [[thread_position_in_grid]]){\n"
"  ulong yhb = C.yh0 + (ulong)tid*C.G;\n"
"  if (yhb >= C.yhEnd) return;\n"
"  ulong yhe = yhb+C.G; if (yhe>C.yhEnd) yhe=C.yhEnd;\n"
"  W PMT=mkw(C.PT0,C.PT1,C.PT2), DEN=mkw(C.PB0,C.PB1x,C.PB2);\n"
"  W PMw=mkw(C.PM0,C.PM1,C.PM2), PSw=mkw(C.PS0,C.PS1,C.PS2), STOP=mkw(C.ST0,C.ST1,C.ST2);\n"
"  W vbase=wmulu(PMT,yhb);\n"
"  if (wcmp(vbase,STOP)>=0) return;\n"
"  W prem; ulong p=wdivbig(vbase,DEN,prem);\n"
"  ulong a0; divq(yhb,C.MQF,C.QF,a0);\n"
"  ulong term3=mod128(mulhi(a0,C.c3f), a0*C.c3f, C.QF);\n"
"  uint recon=0, fulls=0;\n"
"  for (ulong yh=yhb; yh<yhe; yh++){\n"
"    ulong rs=revm(yh,C.b2,C.s,C.Mb2);\n"
"    ulong rsm; divq(rs,C.MQF,C.QF,rsm);\n"
"    ulong Af=term3+rsm; if(Af>=C.QF) Af-=C.QF;\n"
"    W vtop=wsub1(wadd(vbase,PMT));\n"
"    if (wcmp(vtop,STOP)>=0) vtop=wsub1(STOP);\n"
"    for (ulong pp=p;;pp++){\n"
"      W plo=wmulu(DEN,pp);\n"
"      if (wcmp(plo,vtop)>0) break;\n"
"      W phi=wadd(plo,DEN);\n"
"      ulong rjf=revm(pp,C.b1,C.je,C.Mb1);\n"
"      ulong R=rjf>=Af?rjf-Af:rjf+C.QF-Af;\n"
"      ulong keyr; ulong hiq=divq(R,C.MQ,C.Q,keyr);\n"
"      ulong key=keyr; uint needhi=(uint)hiq;\n"
"      uint i0=off[key], i1=off[key+1];\n"
"      for (uint idx=i0; idx<i1; idx++){\n"
"        ulong en=ent[idx];\n"
"        if ((uint)(en&0xffffffff)!=needhi) continue;\n"
"        ulong yl=en>>32;\n"
"        recon++;\n"
"        ulong xr=yl; if(C.odd){ ulong rr0; xr=divq(yl,C.Mb2,C.b2,rr0); }\n"
"        uint td=C.odd? C.t-1 : C.t;\n"
"        ulong rt=revm(xr,C.b2,td,C.Mb2);\n"
"        W v=wadd(wadd(vbase,wmulu(PMw,yl)),wmulu(PSw,rt)); v=waddu(v,rs);\n"
"        if (wcmp(v,plo)<0 || wcmp(v,phi)>=0) continue;\n"
"        if (wcmp(v,STOP)>=0) continue;\n"
"        fulls++;\n"
"        W w=v; ulong rhi=0, rlo=0;\n"
"        for (uint i=0;i<C.kdig;i++){\n"
"          ulong r64=0; ulong limb;\n"
"          limb=w.d2; { ulong a=(r64<<32)|(limb>>32); ulong q1=divq(a,C.Mb1,C.b1,r64); ulong bl=(r64<<32)|(limb&0xffffffff); ulong q0=divq(bl,C.Mb1,C.b1,r64); w.d2=(q1<<32)|q0; }\n"
"          limb=w.d1; { ulong a=(r64<<32)|(limb>>32); ulong q1=divq(a,C.Mb1,C.b1,r64); ulong bl=(r64<<32)|(limb&0xffffffff); ulong q0=divq(bl,C.Mb1,C.b1,r64); w.d1=(q1<<32)|q0; }\n"
"          limb=w.d0; { ulong a=(r64<<32)|(limb>>32); ulong q1=divq(a,C.Mb1,C.b1,r64); ulong bl=(r64<<32)|(limb&0xffffffff); ulong q0=divq(bl,C.Mb1,C.b1,r64); w.d0=(q1<<32)|q0; }\n"
"          ulong dg=r64;\n"
"          ulong nl=rlo*C.b1+dg; ulong nh=rhi*C.b1+mulhi(rlo,(ulong)C.b1);\n"
"          if (nl<dg) nh++;\n"
"          rlo=nl; rhi=nh; }\n"
"        if (C.odd){ ulong r64=0; ulong limb;\n"
"          limb=w.d2; { ulong a=(r64<<32)|(limb>>32); ulong q1=divq(a,C.Mb1,C.b1,r64); ulong bl=(r64<<32)|(limb&0xffffffff); ulong q0=divq(bl,C.Mb1,C.b1,r64); w.d2=(q1<<32)|q0; }\n"
"          limb=w.d1; { ulong a=(r64<<32)|(limb>>32); ulong q1=divq(a,C.Mb1,C.b1,r64); ulong bl=(r64<<32)|(limb&0xffffffff); ulong q0=divq(bl,C.Mb1,C.b1,r64); w.d1=(q1<<32)|q0; }\n"
"          limb=w.d0; { ulong a=(r64<<32)|(limb>>32); ulong q1=divq(a,C.Mb1,C.b1,r64); ulong bl=(r64<<32)|(limb&0xffffffff); ulong q0=divq(bl,C.Mb1,C.b1,r64); w.d0=(q1<<32)|q0; }\n"
"        }\n"
"        if ((w.d2==0) && (w.d1==rhi) && (w.d0==rlo)){\n"
"          uint slot=atomic_fetch_add_explicit(outN,1u,memory_order_relaxed);\n"
"          if (slot<C.outCap){ outP[2*slot]=yh; outP[2*slot+1]=yl; } }\n"
"      }\n"
"    }\n"
"    vbase=wadd(vbase,PMT);\n"
"    prem=wadd(prem,PMT);\n"
"    while (wcmp(prem,DEN)>=0){ prem=wsub(prem,DEN); p++; }\n"
"    term3+=C.c3f; if(term3>=C.QF) term3-=C.QF;\n"
"    if (wcmp(vbase,STOP)>=0) break;\n"
"  }\n"
"  if (recon) atomic_fetch_add_explicit(&stats[0],recon,memory_order_relaxed);\n"
"  if (fulls) atomic_fetch_add_explicit(&stats[1],fulls,memory_order_relaxed);\n"
"}\n";

